// Code generated by ent, DO NOT EDIT.

package node

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the node type in the database.
	Label = "node"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "node_id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldBody holds the string denoting the body field in the database.
	FieldBody = "body"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldParentID holds the string denoting the parent_id field in the database.
	FieldParentID = "parent_id"
	// EdgeParent holds the string denoting the parent edge name in mutations.
	EdgeParent = "parent"
	// EdgeChildren holds the string denoting the children edge name in mutations.
	EdgeChildren = "children"
	// EdgeChildClosures holds the string denoting the child_closures edge name in mutations.
	EdgeChildClosures = "child_closures"
	// EdgeParentClosures holds the string denoting the parent_closures edge name in mutations.
	EdgeParentClosures = "parent_closures"
	// EdgeOutgoingAssociations holds the string denoting the outgoing_associations edge name in mutations.
	EdgeOutgoingAssociations = "outgoing_associations"
	// EdgeIncomingAssociations holds the string denoting the incoming_associations edge name in mutations.
	EdgeIncomingAssociations = "incoming_associations"
	// EdgeFsrsCard holds the string denoting the fsrs_card edge name in mutations.
	EdgeFsrsCard = "fsrs_card"
	// EdgeErrorResolutions holds the string denoting the error_resolutions edge name in mutations.
	EdgeErrorResolutions = "error_resolutions"
	// NodeClosureFieldID holds the string denoting the ID field of the NodeClosure.
	NodeClosureFieldID = "id"
	// NodeAssociationFieldID holds the string denoting the ID field of the NodeAssociation.
	NodeAssociationFieldID = "id"
	// FsrsCardFieldID holds the string denoting the ID field of the FsrsCard.
	FsrsCardFieldID = "card_id"
	// ErrorResolutionFieldID holds the string denoting the ID field of the ErrorResolution.
	ErrorResolutionFieldID = "resolution_id"
	// Table holds the table name of the node in the database.
	Table = "nodes"
	// ParentTable is the table that holds the parent relation/edge.
	ParentTable = "nodes"
	// ParentColumn is the table column denoting the parent relation/edge.
	ParentColumn = "parent_id"
	// ChildrenTable is the table that holds the children relation/edge.
	ChildrenTable = "nodes"
	// ChildrenColumn is the table column denoting the children relation/edge.
	ChildrenColumn = "parent_id"
	// ChildClosuresTable is the table that holds the child_closures relation/edge.
	ChildClosuresTable = "node_closures"
	// ChildClosuresInverseTable is the table name for the NodeClosure entity.
	// It exists in this package in order to avoid circular dependency with the "nodeclosure" package.
	ChildClosuresInverseTable = "node_closures"
	// ChildClosuresColumn is the table column denoting the child_closures relation/edge.
	ChildClosuresColumn = "ancestor_id"
	// ParentClosuresTable is the table that holds the parent_closures relation/edge.
	ParentClosuresTable = "node_closures"
	// ParentClosuresInverseTable is the table name for the NodeClosure entity.
	// It exists in this package in order to avoid circular dependency with the "nodeclosure" package.
	ParentClosuresInverseTable = "node_closures"
	// ParentClosuresColumn is the table column denoting the parent_closures relation/edge.
	ParentClosuresColumn = "descendant_id"
	// OutgoingAssociationsTable is the table that holds the outgoing_associations relation/edge.
	OutgoingAssociationsTable = "node_associations"
	// OutgoingAssociationsInverseTable is the table name for the NodeAssociation entity.
	// It exists in this package in order to avoid circular dependency with the "nodeassociation" package.
	OutgoingAssociationsInverseTable = "node_associations"
	// OutgoingAssociationsColumn is the table column denoting the outgoing_associations relation/edge.
	OutgoingAssociationsColumn = "source_id"
	// IncomingAssociationsTable is the table that holds the incoming_associations relation/edge.
	IncomingAssociationsTable = "node_associations"
	// IncomingAssociationsInverseTable is the table name for the NodeAssociation entity.
	// It exists in this package in order to avoid circular dependency with the "nodeassociation" package.
	IncomingAssociationsInverseTable = "node_associations"
	// IncomingAssociationsColumn is the table column denoting the incoming_associations relation/edge.
	IncomingAssociationsColumn = "target_id"
	// FsrsCardTable is the table that holds the fsrs_card relation/edge.
	FsrsCardTable = "fsrs_cards"
	// FsrsCardInverseTable is the table name for the FsrsCard entity.
	// It exists in this package in order to avoid circular dependency with the "fsrscard" package.
	FsrsCardInverseTable = "fsrs_cards"
	// FsrsCardColumn is the table column denoting the fsrs_card relation/edge.
	FsrsCardColumn = "node_id"
	// ErrorResolutionsTable is the table that holds the error_resolutions relation/edge.
	ErrorResolutionsTable = "error_resolutions"
	// ErrorResolutionsInverseTable is the table name for the ErrorResolution entity.
	// It exists in this package in order to avoid circular dependency with the "errorresolution" package.
	ErrorResolutionsInverseTable = "error_resolutions"
	// ErrorResolutionsColumn is the table column denoting the error_resolutions relation/edge.
	ErrorResolutionsColumn = "node_id"
)

// Columns holds all SQL columns for node fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldType,
	FieldBody,
	FieldMetadata,
	FieldCreatedAt,
	FieldParentID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTitle holds the default value on creation for the "title" field.
	DefaultTitle string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Type defines the type for the "type" enum field.
type Type string

// Type values.
const (
	TypeSubject Type = "subject"
	TypeTopic   Type = "topic"
	TypeProblem Type = "problem"
	TypeTheory  Type = "theory"
	TypeTerm    Type = "term"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeSubject, TypeTopic, TypeProblem, TypeTheory, TypeTerm:
		return nil
	default:
		return fmt.Errorf("node: invalid enum value for type field: %q", _type)
	}
}

// OrderOption defines the ordering options for the Node queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByBody orders the results by the body field.
func ByBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBody, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByParentID orders the results by the parent_id field.
func ByParentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentID, opts...).ToFunc()
}

// ByParentField orders the results by parent field.
func ByParentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newParentStep(), sql.OrderByField(field, opts...))
	}
}

// ByChildrenCount orders the results by children count.
func ByChildrenCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChildrenStep(), opts...)
	}
}

// ByChildren orders the results by children terms.
func ByChildren(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChildrenStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByChildClosuresCount orders the results by child_closures count.
func ByChildClosuresCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChildClosuresStep(), opts...)
	}
}

// ByChildClosures orders the results by child_closures terms.
func ByChildClosures(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChildClosuresStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByParentClosuresCount orders the results by parent_closures count.
func ByParentClosuresCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newParentClosuresStep(), opts...)
	}
}

// ByParentClosures orders the results by parent_closures terms.
func ByParentClosures(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newParentClosuresStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByOutgoingAssociationsCount orders the results by outgoing_associations count.
func ByOutgoingAssociationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOutgoingAssociationsStep(), opts...)
	}
}

// ByOutgoingAssociations orders the results by outgoing_associations terms.
func ByOutgoingAssociations(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOutgoingAssociationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByIncomingAssociationsCount orders the results by incoming_associations count.
func ByIncomingAssociationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newIncomingAssociationsStep(), opts...)
	}
}

// ByIncomingAssociations orders the results by incoming_associations terms.
func ByIncomingAssociations(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newIncomingAssociationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByFsrsCardField orders the results by fsrs_card field.
func ByFsrsCardField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFsrsCardStep(), sql.OrderByField(field, opts...))
	}
}

// ByErrorResolutionsCount orders the results by error_resolutions count.
func ByErrorResolutionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newErrorResolutionsStep(), opts...)
	}
}

// ByErrorResolutions orders the results by error_resolutions terms.
func ByErrorResolutions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newErrorResolutionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newParentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ParentTable, ParentColumn),
	)
}
func newChildrenStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ChildrenTable, ChildrenColumn),
	)
}
func newChildClosuresStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChildClosuresInverseTable, NodeClosureFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ChildClosuresTable, ChildClosuresColumn),
	)
}
func newParentClosuresStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ParentClosuresInverseTable, NodeClosureFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ParentClosuresTable, ParentClosuresColumn),
	)
}
func newOutgoingAssociationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OutgoingAssociationsInverseTable, NodeAssociationFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OutgoingAssociationsTable, OutgoingAssociationsColumn),
	)
}
func newIncomingAssociationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(IncomingAssociationsInverseTable, NodeAssociationFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, IncomingAssociationsTable, IncomingAssociationsColumn),
	)
}
func newFsrsCardStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FsrsCardInverseTable, FsrsCardFieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, FsrsCardTable, FsrsCardColumn),
	)
}
func newErrorResolutionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ErrorResolutionsInverseTable, ErrorResolutionFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ErrorResolutionsTable, ErrorResolutionsColumn),
	)
}
