// Code generated by ent, DO NOT EDIT.

package errordefinition

import (
	"profen/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldLTE(FieldID, id))
}

// BaseWeight applies equality check predicate on the "base_weight" field. It's identical to BaseWeightEQ.
func BaseWeight(v float64) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldEQ(FieldBaseWeight, v))
}

// IsSystem applies equality check predicate on the "is_system" field. It's identical to IsSystemEQ.
func IsSystem(v bool) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldEQ(FieldIsSystem, v))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldContainsFold(FieldLabel, v))
}

// BaseWeightEQ applies the EQ predicate on the "base_weight" field.
func BaseWeightEQ(v float64) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldEQ(FieldBaseWeight, v))
}

// BaseWeightNEQ applies the NEQ predicate on the "base_weight" field.
func BaseWeightNEQ(v float64) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldNEQ(FieldBaseWeight, v))
}

// BaseWeightIn applies the In predicate on the "base_weight" field.
func BaseWeightIn(vs ...float64) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldIn(FieldBaseWeight, vs...))
}

// BaseWeightNotIn applies the NotIn predicate on the "base_weight" field.
func BaseWeightNotIn(vs ...float64) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldNotIn(FieldBaseWeight, vs...))
}

// BaseWeightGT applies the GT predicate on the "base_weight" field.
func BaseWeightGT(v float64) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldGT(FieldBaseWeight, v))
}

// BaseWeightGTE applies the GTE predicate on the "base_weight" field.
func BaseWeightGTE(v float64) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldGTE(FieldBaseWeight, v))
}

// BaseWeightLT applies the LT predicate on the "base_weight" field.
func BaseWeightLT(v float64) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldLT(FieldBaseWeight, v))
}

// BaseWeightLTE applies the LTE predicate on the "base_weight" field.
func BaseWeightLTE(v float64) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldLTE(FieldBaseWeight, v))
}

// IsSystemEQ applies the EQ predicate on the "is_system" field.
func IsSystemEQ(v bool) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldEQ(FieldIsSystem, v))
}

// IsSystemNEQ applies the NEQ predicate on the "is_system" field.
func IsSystemNEQ(v bool) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.FieldNEQ(FieldIsSystem, v))
}

// HasAttempts applies the HasEdge predicate on the "attempts" edge.
func HasAttempts() predicate.ErrorDefinition {
	return predicate.ErrorDefinition(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AttemptsTable, AttemptsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAttemptsWith applies the HasEdge predicate on the "attempts" edge with a given conditions (other predicates).
func HasAttemptsWith(preds ...predicate.Attempt) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(func(s *sql.Selector) {
		step := newAttemptsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ErrorDefinition) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ErrorDefinition) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ErrorDefinition) predicate.ErrorDefinition {
	return predicate.ErrorDefinition(sql.NotPredicates(p))
}
