// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"profen/internal/data/ent/migrate"

	"profen/internal/data/ent/attempt"
	"profen/internal/data/ent/errorresolution"
	"profen/internal/data/ent/errortype"
	"profen/internal/data/ent/fsrscard"
	"profen/internal/data/ent/node"
	"profen/internal/data/ent/nodeassociation"
	"profen/internal/data/ent/nodeclosure"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Attempt is the client for interacting with the Attempt builders.
	Attempt *AttemptClient
	// ErrorResolution is the client for interacting with the ErrorResolution builders.
	ErrorResolution *ErrorResolutionClient
	// ErrorType is the client for interacting with the ErrorType builders.
	ErrorType *ErrorTypeClient
	// FsrsCard is the client for interacting with the FsrsCard builders.
	FsrsCard *FsrsCardClient
	// Node is the client for interacting with the Node builders.
	Node *NodeClient
	// NodeAssociation is the client for interacting with the NodeAssociation builders.
	NodeAssociation *NodeAssociationClient
	// NodeClosure is the client for interacting with the NodeClosure builders.
	NodeClosure *NodeClosureClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Attempt = NewAttemptClient(c.config)
	c.ErrorResolution = NewErrorResolutionClient(c.config)
	c.ErrorType = NewErrorTypeClient(c.config)
	c.FsrsCard = NewFsrsCardClient(c.config)
	c.Node = NewNodeClient(c.config)
	c.NodeAssociation = NewNodeAssociationClient(c.config)
	c.NodeClosure = NewNodeClosureClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		Attempt:         NewAttemptClient(cfg),
		ErrorResolution: NewErrorResolutionClient(cfg),
		ErrorType:       NewErrorTypeClient(cfg),
		FsrsCard:        NewFsrsCardClient(cfg),
		Node:            NewNodeClient(cfg),
		NodeAssociation: NewNodeAssociationClient(cfg),
		NodeClosure:     NewNodeClosureClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		Attempt:         NewAttemptClient(cfg),
		ErrorResolution: NewErrorResolutionClient(cfg),
		ErrorType:       NewErrorTypeClient(cfg),
		FsrsCard:        NewFsrsCardClient(cfg),
		Node:            NewNodeClient(cfg),
		NodeAssociation: NewNodeAssociationClient(cfg),
		NodeClosure:     NewNodeClosureClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Attempt.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Attempt, c.ErrorResolution, c.ErrorType, c.FsrsCard, c.Node,
		c.NodeAssociation, c.NodeClosure,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Attempt, c.ErrorResolution, c.ErrorType, c.FsrsCard, c.Node,
		c.NodeAssociation, c.NodeClosure,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AttemptMutation:
		return c.Attempt.mutate(ctx, m)
	case *ErrorResolutionMutation:
		return c.ErrorResolution.mutate(ctx, m)
	case *ErrorTypeMutation:
		return c.ErrorType.mutate(ctx, m)
	case *FsrsCardMutation:
		return c.FsrsCard.mutate(ctx, m)
	case *NodeMutation:
		return c.Node.mutate(ctx, m)
	case *NodeAssociationMutation:
		return c.NodeAssociation.mutate(ctx, m)
	case *NodeClosureMutation:
		return c.NodeClosure.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AttemptClient is a client for the Attempt schema.
type AttemptClient struct {
	config
}

// NewAttemptClient returns a client for the Attempt from the given config.
func NewAttemptClient(c config) *AttemptClient {
	return &AttemptClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `attempt.Hooks(f(g(h())))`.
func (c *AttemptClient) Use(hooks ...Hook) {
	c.hooks.Attempt = append(c.hooks.Attempt, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `attempt.Intercept(f(g(h())))`.
func (c *AttemptClient) Intercept(interceptors ...Interceptor) {
	c.inters.Attempt = append(c.inters.Attempt, interceptors...)
}

// Create returns a builder for creating a Attempt entity.
func (c *AttemptClient) Create() *AttemptCreate {
	mutation := newAttemptMutation(c.config, OpCreate)
	return &AttemptCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Attempt entities.
func (c *AttemptClient) CreateBulk(builders ...*AttemptCreate) *AttemptCreateBulk {
	return &AttemptCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AttemptClient) MapCreateBulk(slice any, setFunc func(*AttemptCreate, int)) *AttemptCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AttemptCreateBulk{err: fmt.Errorf("calling to AttemptClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AttemptCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AttemptCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Attempt.
func (c *AttemptClient) Update() *AttemptUpdate {
	mutation := newAttemptMutation(c.config, OpUpdate)
	return &AttemptUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AttemptClient) UpdateOne(_m *Attempt) *AttemptUpdateOne {
	mutation := newAttemptMutation(c.config, OpUpdateOne, withAttempt(_m))
	return &AttemptUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AttemptClient) UpdateOneID(id int) *AttemptUpdateOne {
	mutation := newAttemptMutation(c.config, OpUpdateOne, withAttemptID(id))
	return &AttemptUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Attempt.
func (c *AttemptClient) Delete() *AttemptDelete {
	mutation := newAttemptMutation(c.config, OpDelete)
	return &AttemptDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AttemptClient) DeleteOne(_m *Attempt) *AttemptDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AttemptClient) DeleteOneID(id int) *AttemptDeleteOne {
	builder := c.Delete().Where(attempt.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AttemptDeleteOne{builder}
}

// Query returns a query builder for Attempt.
func (c *AttemptClient) Query() *AttemptQuery {
	return &AttemptQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAttempt},
		inters: c.Interceptors(),
	}
}

// Get returns a Attempt entity by its id.
func (c *AttemptClient) Get(ctx context.Context, id int) (*Attempt, error) {
	return c.Query().Where(attempt.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AttemptClient) GetX(ctx context.Context, id int) *Attempt {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AttemptClient) Hooks() []Hook {
	return c.hooks.Attempt
}

// Interceptors returns the client interceptors.
func (c *AttemptClient) Interceptors() []Interceptor {
	return c.inters.Attempt
}

func (c *AttemptClient) mutate(ctx context.Context, m *AttemptMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AttemptCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AttemptUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AttemptUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AttemptDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Attempt mutation op: %q", m.Op())
	}
}

// ErrorResolutionClient is a client for the ErrorResolution schema.
type ErrorResolutionClient struct {
	config
}

// NewErrorResolutionClient returns a client for the ErrorResolution from the given config.
func NewErrorResolutionClient(c config) *ErrorResolutionClient {
	return &ErrorResolutionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `errorresolution.Hooks(f(g(h())))`.
func (c *ErrorResolutionClient) Use(hooks ...Hook) {
	c.hooks.ErrorResolution = append(c.hooks.ErrorResolution, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `errorresolution.Intercept(f(g(h())))`.
func (c *ErrorResolutionClient) Intercept(interceptors ...Interceptor) {
	c.inters.ErrorResolution = append(c.inters.ErrorResolution, interceptors...)
}

// Create returns a builder for creating a ErrorResolution entity.
func (c *ErrorResolutionClient) Create() *ErrorResolutionCreate {
	mutation := newErrorResolutionMutation(c.config, OpCreate)
	return &ErrorResolutionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ErrorResolution entities.
func (c *ErrorResolutionClient) CreateBulk(builders ...*ErrorResolutionCreate) *ErrorResolutionCreateBulk {
	return &ErrorResolutionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ErrorResolutionClient) MapCreateBulk(slice any, setFunc func(*ErrorResolutionCreate, int)) *ErrorResolutionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ErrorResolutionCreateBulk{err: fmt.Errorf("calling to ErrorResolutionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ErrorResolutionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ErrorResolutionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ErrorResolution.
func (c *ErrorResolutionClient) Update() *ErrorResolutionUpdate {
	mutation := newErrorResolutionMutation(c.config, OpUpdate)
	return &ErrorResolutionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ErrorResolutionClient) UpdateOne(_m *ErrorResolution) *ErrorResolutionUpdateOne {
	mutation := newErrorResolutionMutation(c.config, OpUpdateOne, withErrorResolution(_m))
	return &ErrorResolutionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ErrorResolutionClient) UpdateOneID(id int) *ErrorResolutionUpdateOne {
	mutation := newErrorResolutionMutation(c.config, OpUpdateOne, withErrorResolutionID(id))
	return &ErrorResolutionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ErrorResolution.
func (c *ErrorResolutionClient) Delete() *ErrorResolutionDelete {
	mutation := newErrorResolutionMutation(c.config, OpDelete)
	return &ErrorResolutionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ErrorResolutionClient) DeleteOne(_m *ErrorResolution) *ErrorResolutionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ErrorResolutionClient) DeleteOneID(id int) *ErrorResolutionDeleteOne {
	builder := c.Delete().Where(errorresolution.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ErrorResolutionDeleteOne{builder}
}

// Query returns a query builder for ErrorResolution.
func (c *ErrorResolutionClient) Query() *ErrorResolutionQuery {
	return &ErrorResolutionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeErrorResolution},
		inters: c.Interceptors(),
	}
}

// Get returns a ErrorResolution entity by its id.
func (c *ErrorResolutionClient) Get(ctx context.Context, id int) (*ErrorResolution, error) {
	return c.Query().Where(errorresolution.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ErrorResolutionClient) GetX(ctx context.Context, id int) *ErrorResolution {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ErrorResolutionClient) Hooks() []Hook {
	return c.hooks.ErrorResolution
}

// Interceptors returns the client interceptors.
func (c *ErrorResolutionClient) Interceptors() []Interceptor {
	return c.inters.ErrorResolution
}

func (c *ErrorResolutionClient) mutate(ctx context.Context, m *ErrorResolutionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ErrorResolutionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ErrorResolutionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ErrorResolutionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ErrorResolutionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ErrorResolution mutation op: %q", m.Op())
	}
}

// ErrorTypeClient is a client for the ErrorType schema.
type ErrorTypeClient struct {
	config
}

// NewErrorTypeClient returns a client for the ErrorType from the given config.
func NewErrorTypeClient(c config) *ErrorTypeClient {
	return &ErrorTypeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `errortype.Hooks(f(g(h())))`.
func (c *ErrorTypeClient) Use(hooks ...Hook) {
	c.hooks.ErrorType = append(c.hooks.ErrorType, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `errortype.Intercept(f(g(h())))`.
func (c *ErrorTypeClient) Intercept(interceptors ...Interceptor) {
	c.inters.ErrorType = append(c.inters.ErrorType, interceptors...)
}

// Create returns a builder for creating a ErrorType entity.
func (c *ErrorTypeClient) Create() *ErrorTypeCreate {
	mutation := newErrorTypeMutation(c.config, OpCreate)
	return &ErrorTypeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ErrorType entities.
func (c *ErrorTypeClient) CreateBulk(builders ...*ErrorTypeCreate) *ErrorTypeCreateBulk {
	return &ErrorTypeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ErrorTypeClient) MapCreateBulk(slice any, setFunc func(*ErrorTypeCreate, int)) *ErrorTypeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ErrorTypeCreateBulk{err: fmt.Errorf("calling to ErrorTypeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ErrorTypeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ErrorTypeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ErrorType.
func (c *ErrorTypeClient) Update() *ErrorTypeUpdate {
	mutation := newErrorTypeMutation(c.config, OpUpdate)
	return &ErrorTypeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ErrorTypeClient) UpdateOne(_m *ErrorType) *ErrorTypeUpdateOne {
	mutation := newErrorTypeMutation(c.config, OpUpdateOne, withErrorType(_m))
	return &ErrorTypeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ErrorTypeClient) UpdateOneID(id int) *ErrorTypeUpdateOne {
	mutation := newErrorTypeMutation(c.config, OpUpdateOne, withErrorTypeID(id))
	return &ErrorTypeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ErrorType.
func (c *ErrorTypeClient) Delete() *ErrorTypeDelete {
	mutation := newErrorTypeMutation(c.config, OpDelete)
	return &ErrorTypeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ErrorTypeClient) DeleteOne(_m *ErrorType) *ErrorTypeDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ErrorTypeClient) DeleteOneID(id int) *ErrorTypeDeleteOne {
	builder := c.Delete().Where(errortype.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ErrorTypeDeleteOne{builder}
}

// Query returns a query builder for ErrorType.
func (c *ErrorTypeClient) Query() *ErrorTypeQuery {
	return &ErrorTypeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeErrorType},
		inters: c.Interceptors(),
	}
}

// Get returns a ErrorType entity by its id.
func (c *ErrorTypeClient) Get(ctx context.Context, id int) (*ErrorType, error) {
	return c.Query().Where(errortype.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ErrorTypeClient) GetX(ctx context.Context, id int) *ErrorType {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ErrorTypeClient) Hooks() []Hook {
	return c.hooks.ErrorType
}

// Interceptors returns the client interceptors.
func (c *ErrorTypeClient) Interceptors() []Interceptor {
	return c.inters.ErrorType
}

func (c *ErrorTypeClient) mutate(ctx context.Context, m *ErrorTypeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ErrorTypeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ErrorTypeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ErrorTypeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ErrorTypeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ErrorType mutation op: %q", m.Op())
	}
}

// FsrsCardClient is a client for the FsrsCard schema.
type FsrsCardClient struct {
	config
}

// NewFsrsCardClient returns a client for the FsrsCard from the given config.
func NewFsrsCardClient(c config) *FsrsCardClient {
	return &FsrsCardClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `fsrscard.Hooks(f(g(h())))`.
func (c *FsrsCardClient) Use(hooks ...Hook) {
	c.hooks.FsrsCard = append(c.hooks.FsrsCard, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `fsrscard.Intercept(f(g(h())))`.
func (c *FsrsCardClient) Intercept(interceptors ...Interceptor) {
	c.inters.FsrsCard = append(c.inters.FsrsCard, interceptors...)
}

// Create returns a builder for creating a FsrsCard entity.
func (c *FsrsCardClient) Create() *FsrsCardCreate {
	mutation := newFsrsCardMutation(c.config, OpCreate)
	return &FsrsCardCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of FsrsCard entities.
func (c *FsrsCardClient) CreateBulk(builders ...*FsrsCardCreate) *FsrsCardCreateBulk {
	return &FsrsCardCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *FsrsCardClient) MapCreateBulk(slice any, setFunc func(*FsrsCardCreate, int)) *FsrsCardCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &FsrsCardCreateBulk{err: fmt.Errorf("calling to FsrsCardClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*FsrsCardCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &FsrsCardCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for FsrsCard.
func (c *FsrsCardClient) Update() *FsrsCardUpdate {
	mutation := newFsrsCardMutation(c.config, OpUpdate)
	return &FsrsCardUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FsrsCardClient) UpdateOne(_m *FsrsCard) *FsrsCardUpdateOne {
	mutation := newFsrsCardMutation(c.config, OpUpdateOne, withFsrsCard(_m))
	return &FsrsCardUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FsrsCardClient) UpdateOneID(id uuid.UUID) *FsrsCardUpdateOne {
	mutation := newFsrsCardMutation(c.config, OpUpdateOne, withFsrsCardID(id))
	return &FsrsCardUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for FsrsCard.
func (c *FsrsCardClient) Delete() *FsrsCardDelete {
	mutation := newFsrsCardMutation(c.config, OpDelete)
	return &FsrsCardDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FsrsCardClient) DeleteOne(_m *FsrsCard) *FsrsCardDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FsrsCardClient) DeleteOneID(id uuid.UUID) *FsrsCardDeleteOne {
	builder := c.Delete().Where(fsrscard.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FsrsCardDeleteOne{builder}
}

// Query returns a query builder for FsrsCard.
func (c *FsrsCardClient) Query() *FsrsCardQuery {
	return &FsrsCardQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeFsrsCard},
		inters: c.Interceptors(),
	}
}

// Get returns a FsrsCard entity by its id.
func (c *FsrsCardClient) Get(ctx context.Context, id uuid.UUID) (*FsrsCard, error) {
	return c.Query().Where(fsrscard.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FsrsCardClient) GetX(ctx context.Context, id uuid.UUID) *FsrsCard {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryNode queries the node edge of a FsrsCard.
func (c *FsrsCardClient) QueryNode(_m *FsrsCard) *NodeQuery {
	query := (&NodeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(fsrscard.Table, fsrscard.FieldID, id),
			sqlgraph.To(node.Table, node.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, fsrscard.NodeTable, fsrscard.NodeColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *FsrsCardClient) Hooks() []Hook {
	return c.hooks.FsrsCard
}

// Interceptors returns the client interceptors.
func (c *FsrsCardClient) Interceptors() []Interceptor {
	return c.inters.FsrsCard
}

func (c *FsrsCardClient) mutate(ctx context.Context, m *FsrsCardMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&FsrsCardCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&FsrsCardUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&FsrsCardUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&FsrsCardDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown FsrsCard mutation op: %q", m.Op())
	}
}

// NodeClient is a client for the Node schema.
type NodeClient struct {
	config
}

// NewNodeClient returns a client for the Node from the given config.
func NewNodeClient(c config) *NodeClient {
	return &NodeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `node.Hooks(f(g(h())))`.
func (c *NodeClient) Use(hooks ...Hook) {
	c.hooks.Node = append(c.hooks.Node, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `node.Intercept(f(g(h())))`.
func (c *NodeClient) Intercept(interceptors ...Interceptor) {
	c.inters.Node = append(c.inters.Node, interceptors...)
}

// Create returns a builder for creating a Node entity.
func (c *NodeClient) Create() *NodeCreate {
	mutation := newNodeMutation(c.config, OpCreate)
	return &NodeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Node entities.
func (c *NodeClient) CreateBulk(builders ...*NodeCreate) *NodeCreateBulk {
	return &NodeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *NodeClient) MapCreateBulk(slice any, setFunc func(*NodeCreate, int)) *NodeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &NodeCreateBulk{err: fmt.Errorf("calling to NodeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*NodeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &NodeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Node.
func (c *NodeClient) Update() *NodeUpdate {
	mutation := newNodeMutation(c.config, OpUpdate)
	return &NodeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NodeClient) UpdateOne(_m *Node) *NodeUpdateOne {
	mutation := newNodeMutation(c.config, OpUpdateOne, withNode(_m))
	return &NodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NodeClient) UpdateOneID(id uuid.UUID) *NodeUpdateOne {
	mutation := newNodeMutation(c.config, OpUpdateOne, withNodeID(id))
	return &NodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Node.
func (c *NodeClient) Delete() *NodeDelete {
	mutation := newNodeMutation(c.config, OpDelete)
	return &NodeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *NodeClient) DeleteOne(_m *Node) *NodeDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *NodeClient) DeleteOneID(id uuid.UUID) *NodeDeleteOne {
	builder := c.Delete().Where(node.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NodeDeleteOne{builder}
}

// Query returns a query builder for Node.
func (c *NodeClient) Query() *NodeQuery {
	return &NodeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeNode},
		inters: c.Interceptors(),
	}
}

// Get returns a Node entity by its id.
func (c *NodeClient) Get(ctx context.Context, id uuid.UUID) (*Node, error) {
	return c.Query().Where(node.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NodeClient) GetX(ctx context.Context, id uuid.UUID) *Node {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryParent queries the parent edge of a Node.
func (c *NodeClient) QueryParent(_m *Node) *NodeQuery {
	query := (&NodeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(node.Table, node.FieldID, id),
			sqlgraph.To(node.Table, node.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, node.ParentTable, node.ParentColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryChildren queries the children edge of a Node.
func (c *NodeClient) QueryChildren(_m *Node) *NodeQuery {
	query := (&NodeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(node.Table, node.FieldID, id),
			sqlgraph.To(node.Table, node.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, node.ChildrenTable, node.ChildrenColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryChildClosures queries the child_closures edge of a Node.
func (c *NodeClient) QueryChildClosures(_m *Node) *NodeClosureQuery {
	query := (&NodeClosureClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(node.Table, node.FieldID, id),
			sqlgraph.To(nodeclosure.Table, nodeclosure.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, node.ChildClosuresTable, node.ChildClosuresColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryParentClosures queries the parent_closures edge of a Node.
func (c *NodeClient) QueryParentClosures(_m *Node) *NodeClosureQuery {
	query := (&NodeClosureClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(node.Table, node.FieldID, id),
			sqlgraph.To(nodeclosure.Table, nodeclosure.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, node.ParentClosuresTable, node.ParentClosuresColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryOutgoingAssociations queries the outgoing_associations edge of a Node.
func (c *NodeClient) QueryOutgoingAssociations(_m *Node) *NodeAssociationQuery {
	query := (&NodeAssociationClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(node.Table, node.FieldID, id),
			sqlgraph.To(nodeassociation.Table, nodeassociation.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, node.OutgoingAssociationsTable, node.OutgoingAssociationsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryIncomingAssociations queries the incoming_associations edge of a Node.
func (c *NodeClient) QueryIncomingAssociations(_m *Node) *NodeAssociationQuery {
	query := (&NodeAssociationClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(node.Table, node.FieldID, id),
			sqlgraph.To(nodeassociation.Table, nodeassociation.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, node.IncomingAssociationsTable, node.IncomingAssociationsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryFsrsCard queries the fsrs_card edge of a Node.
func (c *NodeClient) QueryFsrsCard(_m *Node) *FsrsCardQuery {
	query := (&FsrsCardClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(node.Table, node.FieldID, id),
			sqlgraph.To(fsrscard.Table, fsrscard.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, node.FsrsCardTable, node.FsrsCardColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *NodeClient) Hooks() []Hook {
	return c.hooks.Node
}

// Interceptors returns the client interceptors.
func (c *NodeClient) Interceptors() []Interceptor {
	return c.inters.Node
}

func (c *NodeClient) mutate(ctx context.Context, m *NodeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&NodeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&NodeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&NodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&NodeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Node mutation op: %q", m.Op())
	}
}

// NodeAssociationClient is a client for the NodeAssociation schema.
type NodeAssociationClient struct {
	config
}

// NewNodeAssociationClient returns a client for the NodeAssociation from the given config.
func NewNodeAssociationClient(c config) *NodeAssociationClient {
	return &NodeAssociationClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `nodeassociation.Hooks(f(g(h())))`.
func (c *NodeAssociationClient) Use(hooks ...Hook) {
	c.hooks.NodeAssociation = append(c.hooks.NodeAssociation, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `nodeassociation.Intercept(f(g(h())))`.
func (c *NodeAssociationClient) Intercept(interceptors ...Interceptor) {
	c.inters.NodeAssociation = append(c.inters.NodeAssociation, interceptors...)
}

// Create returns a builder for creating a NodeAssociation entity.
func (c *NodeAssociationClient) Create() *NodeAssociationCreate {
	mutation := newNodeAssociationMutation(c.config, OpCreate)
	return &NodeAssociationCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of NodeAssociation entities.
func (c *NodeAssociationClient) CreateBulk(builders ...*NodeAssociationCreate) *NodeAssociationCreateBulk {
	return &NodeAssociationCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *NodeAssociationClient) MapCreateBulk(slice any, setFunc func(*NodeAssociationCreate, int)) *NodeAssociationCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &NodeAssociationCreateBulk{err: fmt.Errorf("calling to NodeAssociationClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*NodeAssociationCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &NodeAssociationCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for NodeAssociation.
func (c *NodeAssociationClient) Update() *NodeAssociationUpdate {
	mutation := newNodeAssociationMutation(c.config, OpUpdate)
	return &NodeAssociationUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NodeAssociationClient) UpdateOne(_m *NodeAssociation) *NodeAssociationUpdateOne {
	mutation := newNodeAssociationMutation(c.config, OpUpdateOne, withNodeAssociation(_m))
	return &NodeAssociationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NodeAssociationClient) UpdateOneID(id int) *NodeAssociationUpdateOne {
	mutation := newNodeAssociationMutation(c.config, OpUpdateOne, withNodeAssociationID(id))
	return &NodeAssociationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for NodeAssociation.
func (c *NodeAssociationClient) Delete() *NodeAssociationDelete {
	mutation := newNodeAssociationMutation(c.config, OpDelete)
	return &NodeAssociationDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *NodeAssociationClient) DeleteOne(_m *NodeAssociation) *NodeAssociationDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *NodeAssociationClient) DeleteOneID(id int) *NodeAssociationDeleteOne {
	builder := c.Delete().Where(nodeassociation.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NodeAssociationDeleteOne{builder}
}

// Query returns a query builder for NodeAssociation.
func (c *NodeAssociationClient) Query() *NodeAssociationQuery {
	return &NodeAssociationQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeNodeAssociation},
		inters: c.Interceptors(),
	}
}

// Get returns a NodeAssociation entity by its id.
func (c *NodeAssociationClient) Get(ctx context.Context, id int) (*NodeAssociation, error) {
	return c.Query().Where(nodeassociation.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NodeAssociationClient) GetX(ctx context.Context, id int) *NodeAssociation {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySource queries the source edge of a NodeAssociation.
func (c *NodeAssociationClient) QuerySource(_m *NodeAssociation) *NodeQuery {
	query := (&NodeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(nodeassociation.Table, nodeassociation.FieldID, id),
			sqlgraph.To(node.Table, node.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, nodeassociation.SourceTable, nodeassociation.SourceColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTarget queries the target edge of a NodeAssociation.
func (c *NodeAssociationClient) QueryTarget(_m *NodeAssociation) *NodeQuery {
	query := (&NodeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(nodeassociation.Table, nodeassociation.FieldID, id),
			sqlgraph.To(node.Table, node.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, nodeassociation.TargetTable, nodeassociation.TargetColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *NodeAssociationClient) Hooks() []Hook {
	return c.hooks.NodeAssociation
}

// Interceptors returns the client interceptors.
func (c *NodeAssociationClient) Interceptors() []Interceptor {
	return c.inters.NodeAssociation
}

func (c *NodeAssociationClient) mutate(ctx context.Context, m *NodeAssociationMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&NodeAssociationCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&NodeAssociationUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&NodeAssociationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&NodeAssociationDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown NodeAssociation mutation op: %q", m.Op())
	}
}

// NodeClosureClient is a client for the NodeClosure schema.
type NodeClosureClient struct {
	config
}

// NewNodeClosureClient returns a client for the NodeClosure from the given config.
func NewNodeClosureClient(c config) *NodeClosureClient {
	return &NodeClosureClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `nodeclosure.Hooks(f(g(h())))`.
func (c *NodeClosureClient) Use(hooks ...Hook) {
	c.hooks.NodeClosure = append(c.hooks.NodeClosure, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `nodeclosure.Intercept(f(g(h())))`.
func (c *NodeClosureClient) Intercept(interceptors ...Interceptor) {
	c.inters.NodeClosure = append(c.inters.NodeClosure, interceptors...)
}

// Create returns a builder for creating a NodeClosure entity.
func (c *NodeClosureClient) Create() *NodeClosureCreate {
	mutation := newNodeClosureMutation(c.config, OpCreate)
	return &NodeClosureCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of NodeClosure entities.
func (c *NodeClosureClient) CreateBulk(builders ...*NodeClosureCreate) *NodeClosureCreateBulk {
	return &NodeClosureCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *NodeClosureClient) MapCreateBulk(slice any, setFunc func(*NodeClosureCreate, int)) *NodeClosureCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &NodeClosureCreateBulk{err: fmt.Errorf("calling to NodeClosureClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*NodeClosureCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &NodeClosureCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for NodeClosure.
func (c *NodeClosureClient) Update() *NodeClosureUpdate {
	mutation := newNodeClosureMutation(c.config, OpUpdate)
	return &NodeClosureUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NodeClosureClient) UpdateOne(_m *NodeClosure) *NodeClosureUpdateOne {
	mutation := newNodeClosureMutation(c.config, OpUpdateOne, withNodeClosure(_m))
	return &NodeClosureUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NodeClosureClient) UpdateOneID(id int) *NodeClosureUpdateOne {
	mutation := newNodeClosureMutation(c.config, OpUpdateOne, withNodeClosureID(id))
	return &NodeClosureUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for NodeClosure.
func (c *NodeClosureClient) Delete() *NodeClosureDelete {
	mutation := newNodeClosureMutation(c.config, OpDelete)
	return &NodeClosureDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *NodeClosureClient) DeleteOne(_m *NodeClosure) *NodeClosureDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *NodeClosureClient) DeleteOneID(id int) *NodeClosureDeleteOne {
	builder := c.Delete().Where(nodeclosure.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NodeClosureDeleteOne{builder}
}

// Query returns a query builder for NodeClosure.
func (c *NodeClosureClient) Query() *NodeClosureQuery {
	return &NodeClosureQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeNodeClosure},
		inters: c.Interceptors(),
	}
}

// Get returns a NodeClosure entity by its id.
func (c *NodeClosureClient) Get(ctx context.Context, id int) (*NodeClosure, error) {
	return c.Query().Where(nodeclosure.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NodeClosureClient) GetX(ctx context.Context, id int) *NodeClosure {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryAncestor queries the ancestor edge of a NodeClosure.
func (c *NodeClosureClient) QueryAncestor(_m *NodeClosure) *NodeQuery {
	query := (&NodeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(nodeclosure.Table, nodeclosure.FieldID, id),
			sqlgraph.To(node.Table, node.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, nodeclosure.AncestorTable, nodeclosure.AncestorColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDescendant queries the descendant edge of a NodeClosure.
func (c *NodeClosureClient) QueryDescendant(_m *NodeClosure) *NodeQuery {
	query := (&NodeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(nodeclosure.Table, nodeclosure.FieldID, id),
			sqlgraph.To(node.Table, node.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, nodeclosure.DescendantTable, nodeclosure.DescendantColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *NodeClosureClient) Hooks() []Hook {
	return c.hooks.NodeClosure
}

// Interceptors returns the client interceptors.
func (c *NodeClosureClient) Interceptors() []Interceptor {
	return c.inters.NodeClosure
}

func (c *NodeClosureClient) mutate(ctx context.Context, m *NodeClosureMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&NodeClosureCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&NodeClosureUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&NodeClosureUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&NodeClosureDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown NodeClosure mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Attempt, ErrorResolution, ErrorType, FsrsCard, Node, NodeAssociation,
		NodeClosure []ent.Hook
	}
	inters struct {
		Attempt, ErrorResolution, ErrorType, FsrsCard, Node, NodeAssociation,
		NodeClosure []ent.Interceptor
	}
)
