// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"profen/internal/data/ent/attempt"
	"profen/internal/data/ent/errordefinition"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ErrorDefinitionCreate is the builder for creating a ErrorDefinition entity.
type ErrorDefinitionCreate struct {
	config
	mutation *ErrorDefinitionMutation
	hooks    []Hook
}

// SetLabel sets the "label" field.
func (_c *ErrorDefinitionCreate) SetLabel(v string) *ErrorDefinitionCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetBaseWeight sets the "base_weight" field.
func (_c *ErrorDefinitionCreate) SetBaseWeight(v float64) *ErrorDefinitionCreate {
	_c.mutation.SetBaseWeight(v)
	return _c
}

// SetNillableBaseWeight sets the "base_weight" field if the given value is not nil.
func (_c *ErrorDefinitionCreate) SetNillableBaseWeight(v *float64) *ErrorDefinitionCreate {
	if v != nil {
		_c.SetBaseWeight(*v)
	}
	return _c
}

// SetIsSystem sets the "is_system" field.
func (_c *ErrorDefinitionCreate) SetIsSystem(v bool) *ErrorDefinitionCreate {
	_c.mutation.SetIsSystem(v)
	return _c
}

// SetNillableIsSystem sets the "is_system" field if the given value is not nil.
func (_c *ErrorDefinitionCreate) SetNillableIsSystem(v *bool) *ErrorDefinitionCreate {
	if v != nil {
		_c.SetIsSystem(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ErrorDefinitionCreate) SetID(v uuid.UUID) *ErrorDefinitionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ErrorDefinitionCreate) SetNillableID(v *uuid.UUID) *ErrorDefinitionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddAttemptIDs adds the "attempts" edge to the Attempt entity by IDs.
func (_c *ErrorDefinitionCreate) AddAttemptIDs(ids ...uuid.UUID) *ErrorDefinitionCreate {
	_c.mutation.AddAttemptIDs(ids...)
	return _c
}

// AddAttempts adds the "attempts" edges to the Attempt entity.
func (_c *ErrorDefinitionCreate) AddAttempts(v ...*Attempt) *ErrorDefinitionCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAttemptIDs(ids...)
}

// Mutation returns the ErrorDefinitionMutation object of the builder.
func (_c *ErrorDefinitionCreate) Mutation() *ErrorDefinitionMutation {
	return _c.mutation
}

// Save creates the ErrorDefinition in the database.
func (_c *ErrorDefinitionCreate) Save(ctx context.Context) (*ErrorDefinition, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ErrorDefinitionCreate) SaveX(ctx context.Context) *ErrorDefinition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ErrorDefinitionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ErrorDefinitionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ErrorDefinitionCreate) defaults() {
	if _, ok := _c.mutation.BaseWeight(); !ok {
		v := errordefinition.DefaultBaseWeight
		_c.mutation.SetBaseWeight(v)
	}
	if _, ok := _c.mutation.IsSystem(); !ok {
		v := errordefinition.DefaultIsSystem
		_c.mutation.SetIsSystem(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := errordefinition.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ErrorDefinitionCreate) check() error {
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "ErrorDefinition.label"`)}
	}
	if v, ok := _c.mutation.Label(); ok {
		if err := errordefinition.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "ErrorDefinition.label": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BaseWeight(); !ok {
		return &ValidationError{Name: "base_weight", err: errors.New(`ent: missing required field "ErrorDefinition.base_weight"`)}
	}
	if _, ok := _c.mutation.IsSystem(); !ok {
		return &ValidationError{Name: "is_system", err: errors.New(`ent: missing required field "ErrorDefinition.is_system"`)}
	}
	return nil
}

func (_c *ErrorDefinitionCreate) sqlSave(ctx context.Context) (*ErrorDefinition, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ErrorDefinitionCreate) createSpec() (*ErrorDefinition, *sqlgraph.CreateSpec) {
	var (
		_node = &ErrorDefinition{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(errordefinition.Table, sqlgraph.NewFieldSpec(errordefinition.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(errordefinition.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.BaseWeight(); ok {
		_spec.SetField(errordefinition.FieldBaseWeight, field.TypeFloat64, value)
		_node.BaseWeight = value
	}
	if value, ok := _c.mutation.IsSystem(); ok {
		_spec.SetField(errordefinition.FieldIsSystem, field.TypeBool, value)
		_node.IsSystem = value
	}
	if nodes := _c.mutation.AttemptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   errordefinition.AttemptsTable,
			Columns: []string{errordefinition.AttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attempt.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ErrorDefinitionCreateBulk is the builder for creating many ErrorDefinition entities in bulk.
type ErrorDefinitionCreateBulk struct {
	config
	err      error
	builders []*ErrorDefinitionCreate
}

// Save creates the ErrorDefinition entities in the database.
func (_c *ErrorDefinitionCreateBulk) Save(ctx context.Context) ([]*ErrorDefinition, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ErrorDefinition, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ErrorDefinitionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ErrorDefinitionCreateBulk) SaveX(ctx context.Context) []*ErrorDefinition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ErrorDefinitionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ErrorDefinitionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
