// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"profen/internal/data/ent/errortype"
	"profen/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ErrorTypeDelete is the builder for deleting a ErrorType entity.
type ErrorTypeDelete struct {
	config
	hooks    []Hook
	mutation *ErrorTypeMutation
}

// Where appends a list predicates to the ErrorTypeDelete builder.
func (_d *ErrorTypeDelete) Where(ps ...predicate.ErrorType) *ErrorTypeDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ErrorTypeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ErrorTypeDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ErrorTypeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(errortype.Table, sqlgraph.NewFieldSpec(errortype.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ErrorTypeDeleteOne is the builder for deleting a single ErrorType entity.
type ErrorTypeDeleteOne struct {
	_d *ErrorTypeDelete
}

// Where appends a list predicates to the ErrorTypeDelete builder.
func (_d *ErrorTypeDeleteOne) Where(ps ...predicate.ErrorType) *ErrorTypeDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ErrorTypeDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{errortype.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ErrorTypeDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
