// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"profen/internal/data/ent/errordefinition"
	"profen/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ErrorDefinitionDelete is the builder for deleting a ErrorDefinition entity.
type ErrorDefinitionDelete struct {
	config
	hooks    []Hook
	mutation *ErrorDefinitionMutation
}

// Where appends a list predicates to the ErrorDefinitionDelete builder.
func (_d *ErrorDefinitionDelete) Where(ps ...predicate.ErrorDefinition) *ErrorDefinitionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ErrorDefinitionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ErrorDefinitionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ErrorDefinitionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(errordefinition.Table, sqlgraph.NewFieldSpec(errordefinition.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ErrorDefinitionDeleteOne is the builder for deleting a single ErrorDefinition entity.
type ErrorDefinitionDeleteOne struct {
	_d *ErrorDefinitionDelete
}

// Where appends a list predicates to the ErrorDefinitionDelete builder.
func (_d *ErrorDefinitionDeleteOne) Where(ps ...predicate.ErrorDefinition) *ErrorDefinitionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ErrorDefinitionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{errordefinition.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ErrorDefinitionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
