// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"profen/internal/data/ent/errorresolution"
	"profen/internal/data/ent/node"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ErrorResolutionCreate is the builder for creating a ErrorResolution entity.
type ErrorResolutionCreate struct {
	config
	mutation *ErrorResolutionMutation
	hooks    []Hook
}

// SetNodeID sets the "node_id" field.
func (_c *ErrorResolutionCreate) SetNodeID(v uuid.UUID) *ErrorResolutionCreate {
	_c.mutation.SetNodeID(v)
	return _c
}

// SetErrorTypeID sets the "error_type_id" field.
func (_c *ErrorResolutionCreate) SetErrorTypeID(v uuid.UUID) *ErrorResolutionCreate {
	_c.mutation.SetErrorTypeID(v)
	return _c
}

// SetWeightImpact sets the "weight_impact" field.
func (_c *ErrorResolutionCreate) SetWeightImpact(v float64) *ErrorResolutionCreate {
	_c.mutation.SetWeightImpact(v)
	return _c
}

// SetNillableWeightImpact sets the "weight_impact" field if the given value is not nil.
func (_c *ErrorResolutionCreate) SetNillableWeightImpact(v *float64) *ErrorResolutionCreate {
	if v != nil {
		_c.SetWeightImpact(*v)
	}
	return _c
}

// SetIsResolved sets the "is_resolved" field.
func (_c *ErrorResolutionCreate) SetIsResolved(v bool) *ErrorResolutionCreate {
	_c.mutation.SetIsResolved(v)
	return _c
}

// SetNillableIsResolved sets the "is_resolved" field if the given value is not nil.
func (_c *ErrorResolutionCreate) SetNillableIsResolved(v *bool) *ErrorResolutionCreate {
	if v != nil {
		_c.SetIsResolved(*v)
	}
	return _c
}

// SetResolutionNotes sets the "resolution_notes" field.
func (_c *ErrorResolutionCreate) SetResolutionNotes(v string) *ErrorResolutionCreate {
	_c.mutation.SetResolutionNotes(v)
	return _c
}

// SetNillableResolutionNotes sets the "resolution_notes" field if the given value is not nil.
func (_c *ErrorResolutionCreate) SetNillableResolutionNotes(v *string) *ErrorResolutionCreate {
	if v != nil {
		_c.SetResolutionNotes(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ErrorResolutionCreate) SetCreatedAt(v time.Time) *ErrorResolutionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ErrorResolutionCreate) SetNillableCreatedAt(v *time.Time) *ErrorResolutionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetResolvedAt sets the "resolved_at" field.
func (_c *ErrorResolutionCreate) SetResolvedAt(v time.Time) *ErrorResolutionCreate {
	_c.mutation.SetResolvedAt(v)
	return _c
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_c *ErrorResolutionCreate) SetNillableResolvedAt(v *time.Time) *ErrorResolutionCreate {
	if v != nil {
		_c.SetResolvedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ErrorResolutionCreate) SetID(v uuid.UUID) *ErrorResolutionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ErrorResolutionCreate) SetNillableID(v *uuid.UUID) *ErrorResolutionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetNode sets the "node" edge to the Node entity.
func (_c *ErrorResolutionCreate) SetNode(v *Node) *ErrorResolutionCreate {
	return _c.SetNodeID(v.ID)
}

// Mutation returns the ErrorResolutionMutation object of the builder.
func (_c *ErrorResolutionCreate) Mutation() *ErrorResolutionMutation {
	return _c.mutation
}

// Save creates the ErrorResolution in the database.
func (_c *ErrorResolutionCreate) Save(ctx context.Context) (*ErrorResolution, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ErrorResolutionCreate) SaveX(ctx context.Context) *ErrorResolution {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ErrorResolutionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ErrorResolutionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ErrorResolutionCreate) defaults() {
	if _, ok := _c.mutation.WeightImpact(); !ok {
		v := errorresolution.DefaultWeightImpact
		_c.mutation.SetWeightImpact(v)
	}
	if _, ok := _c.mutation.IsResolved(); !ok {
		v := errorresolution.DefaultIsResolved
		_c.mutation.SetIsResolved(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := errorresolution.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := errorresolution.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ErrorResolutionCreate) check() error {
	if _, ok := _c.mutation.NodeID(); !ok {
		return &ValidationError{Name: "node_id", err: errors.New(`ent: missing required field "ErrorResolution.node_id"`)}
	}
	if _, ok := _c.mutation.ErrorTypeID(); !ok {
		return &ValidationError{Name: "error_type_id", err: errors.New(`ent: missing required field "ErrorResolution.error_type_id"`)}
	}
	if _, ok := _c.mutation.WeightImpact(); !ok {
		return &ValidationError{Name: "weight_impact", err: errors.New(`ent: missing required field "ErrorResolution.weight_impact"`)}
	}
	if _, ok := _c.mutation.IsResolved(); !ok {
		return &ValidationError{Name: "is_resolved", err: errors.New(`ent: missing required field "ErrorResolution.is_resolved"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ErrorResolution.created_at"`)}
	}
	if len(_c.mutation.NodeIDs()) == 0 {
		return &ValidationError{Name: "node", err: errors.New(`ent: missing required edge "ErrorResolution.node"`)}
	}
	return nil
}

func (_c *ErrorResolutionCreate) sqlSave(ctx context.Context) (*ErrorResolution, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ErrorResolutionCreate) createSpec() (*ErrorResolution, *sqlgraph.CreateSpec) {
	var (
		_node = &ErrorResolution{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(errorresolution.Table, sqlgraph.NewFieldSpec(errorresolution.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.ErrorTypeID(); ok {
		_spec.SetField(errorresolution.FieldErrorTypeID, field.TypeUUID, value)
		_node.ErrorTypeID = value
	}
	if value, ok := _c.mutation.WeightImpact(); ok {
		_spec.SetField(errorresolution.FieldWeightImpact, field.TypeFloat64, value)
		_node.WeightImpact = value
	}
	if value, ok := _c.mutation.IsResolved(); ok {
		_spec.SetField(errorresolution.FieldIsResolved, field.TypeBool, value)
		_node.IsResolved = value
	}
	if value, ok := _c.mutation.ResolutionNotes(); ok {
		_spec.SetField(errorresolution.FieldResolutionNotes, field.TypeString, value)
		_node.ResolutionNotes = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(errorresolution.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ResolvedAt(); ok {
		_spec.SetField(errorresolution.FieldResolvedAt, field.TypeTime, value)
		_node.ResolvedAt = &value
	}
	if nodes := _c.mutation.NodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   errorresolution.NodeTable,
			Columns: []string{errorresolution.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.NodeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ErrorResolutionCreateBulk is the builder for creating many ErrorResolution entities in bulk.
type ErrorResolutionCreateBulk struct {
	config
	err      error
	builders []*ErrorResolutionCreate
}

// Save creates the ErrorResolution entities in the database.
func (_c *ErrorResolutionCreateBulk) Save(ctx context.Context) ([]*ErrorResolution, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ErrorResolution, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ErrorResolutionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ErrorResolutionCreateBulk) SaveX(ctx context.Context) []*ErrorResolution {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ErrorResolutionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ErrorResolutionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
