// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"profen/internal/data/ent/errorresolution"
	"profen/internal/data/ent/node"
	"profen/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ErrorResolutionUpdate is the builder for updating ErrorResolution entities.
type ErrorResolutionUpdate struct {
	config
	hooks     []Hook
	mutation  *ErrorResolutionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ErrorResolutionUpdate builder.
func (_u *ErrorResolutionUpdate) Where(ps ...predicate.ErrorResolution) *ErrorResolutionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetNodeID sets the "node_id" field.
func (_u *ErrorResolutionUpdate) SetNodeID(v uuid.UUID) *ErrorResolutionUpdate {
	_u.mutation.SetNodeID(v)
	return _u
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_u *ErrorResolutionUpdate) SetNillableNodeID(v *uuid.UUID) *ErrorResolutionUpdate {
	if v != nil {
		_u.SetNodeID(*v)
	}
	return _u
}

// SetErrorType sets the "error_type" field.
func (_u *ErrorResolutionUpdate) SetErrorType(v string) *ErrorResolutionUpdate {
	_u.mutation.SetErrorType(v)
	return _u
}

// SetNillableErrorType sets the "error_type" field if the given value is not nil.
func (_u *ErrorResolutionUpdate) SetNillableErrorType(v *string) *ErrorResolutionUpdate {
	if v != nil {
		_u.SetErrorType(*v)
	}
	return _u
}

// SetWeightImpact sets the "weight_impact" field.
func (_u *ErrorResolutionUpdate) SetWeightImpact(v float64) *ErrorResolutionUpdate {
	_u.mutation.ResetWeightImpact()
	_u.mutation.SetWeightImpact(v)
	return _u
}

// SetNillableWeightImpact sets the "weight_impact" field if the given value is not nil.
func (_u *ErrorResolutionUpdate) SetNillableWeightImpact(v *float64) *ErrorResolutionUpdate {
	if v != nil {
		_u.SetWeightImpact(*v)
	}
	return _u
}

// AddWeightImpact adds value to the "weight_impact" field.
func (_u *ErrorResolutionUpdate) AddWeightImpact(v float64) *ErrorResolutionUpdate {
	_u.mutation.AddWeightImpact(v)
	return _u
}

// SetIsResolved sets the "is_resolved" field.
func (_u *ErrorResolutionUpdate) SetIsResolved(v bool) *ErrorResolutionUpdate {
	_u.mutation.SetIsResolved(v)
	return _u
}

// SetNillableIsResolved sets the "is_resolved" field if the given value is not nil.
func (_u *ErrorResolutionUpdate) SetNillableIsResolved(v *bool) *ErrorResolutionUpdate {
	if v != nil {
		_u.SetIsResolved(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ErrorResolutionUpdate) SetCreatedAt(v time.Time) *ErrorResolutionUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ErrorResolutionUpdate) SetNillableCreatedAt(v *time.Time) *ErrorResolutionUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetResolvedAt sets the "resolved_at" field.
func (_u *ErrorResolutionUpdate) SetResolvedAt(v time.Time) *ErrorResolutionUpdate {
	_u.mutation.SetResolvedAt(v)
	return _u
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_u *ErrorResolutionUpdate) SetNillableResolvedAt(v *time.Time) *ErrorResolutionUpdate {
	if v != nil {
		_u.SetResolvedAt(*v)
	}
	return _u
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (_u *ErrorResolutionUpdate) ClearResolvedAt() *ErrorResolutionUpdate {
	_u.mutation.ClearResolvedAt()
	return _u
}

// SetNode sets the "node" edge to the Node entity.
func (_u *ErrorResolutionUpdate) SetNode(v *Node) *ErrorResolutionUpdate {
	return _u.SetNodeID(v.ID)
}

// Mutation returns the ErrorResolutionMutation object of the builder.
func (_u *ErrorResolutionUpdate) Mutation() *ErrorResolutionMutation {
	return _u.mutation
}

// ClearNode clears the "node" edge to the Node entity.
func (_u *ErrorResolutionUpdate) ClearNode() *ErrorResolutionUpdate {
	_u.mutation.ClearNode()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ErrorResolutionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ErrorResolutionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ErrorResolutionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ErrorResolutionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ErrorResolutionUpdate) check() error {
	if v, ok := _u.mutation.ErrorType(); ok {
		if err := errorresolution.ErrorTypeValidator(v); err != nil {
			return &ValidationError{Name: "error_type", err: fmt.Errorf(`ent: validator failed for field "ErrorResolution.error_type": %w`, err)}
		}
	}
	if _u.mutation.NodeCleared() && len(_u.mutation.NodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ErrorResolution.node"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ErrorResolutionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ErrorResolutionUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ErrorResolutionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(errorresolution.Table, errorresolution.Columns, sqlgraph.NewFieldSpec(errorresolution.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ErrorType(); ok {
		_spec.SetField(errorresolution.FieldErrorType, field.TypeString, value)
	}
	if value, ok := _u.mutation.WeightImpact(); ok {
		_spec.SetField(errorresolution.FieldWeightImpact, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeightImpact(); ok {
		_spec.AddField(errorresolution.FieldWeightImpact, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.IsResolved(); ok {
		_spec.SetField(errorresolution.FieldIsResolved, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(errorresolution.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ResolvedAt(); ok {
		_spec.SetField(errorresolution.FieldResolvedAt, field.TypeTime, value)
	}
	if _u.mutation.ResolvedAtCleared() {
		_spec.ClearField(errorresolution.FieldResolvedAt, field.TypeTime)
	}
	if _u.mutation.NodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   errorresolution.NodeTable,
			Columns: []string{errorresolution.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   errorresolution.NodeTable,
			Columns: []string{errorresolution.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{errorresolution.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ErrorResolutionUpdateOne is the builder for updating a single ErrorResolution entity.
type ErrorResolutionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ErrorResolutionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetNodeID sets the "node_id" field.
func (_u *ErrorResolutionUpdateOne) SetNodeID(v uuid.UUID) *ErrorResolutionUpdateOne {
	_u.mutation.SetNodeID(v)
	return _u
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_u *ErrorResolutionUpdateOne) SetNillableNodeID(v *uuid.UUID) *ErrorResolutionUpdateOne {
	if v != nil {
		_u.SetNodeID(*v)
	}
	return _u
}

// SetErrorType sets the "error_type" field.
func (_u *ErrorResolutionUpdateOne) SetErrorType(v string) *ErrorResolutionUpdateOne {
	_u.mutation.SetErrorType(v)
	return _u
}

// SetNillableErrorType sets the "error_type" field if the given value is not nil.
func (_u *ErrorResolutionUpdateOne) SetNillableErrorType(v *string) *ErrorResolutionUpdateOne {
	if v != nil {
		_u.SetErrorType(*v)
	}
	return _u
}

// SetWeightImpact sets the "weight_impact" field.
func (_u *ErrorResolutionUpdateOne) SetWeightImpact(v float64) *ErrorResolutionUpdateOne {
	_u.mutation.ResetWeightImpact()
	_u.mutation.SetWeightImpact(v)
	return _u
}

// SetNillableWeightImpact sets the "weight_impact" field if the given value is not nil.
func (_u *ErrorResolutionUpdateOne) SetNillableWeightImpact(v *float64) *ErrorResolutionUpdateOne {
	if v != nil {
		_u.SetWeightImpact(*v)
	}
	return _u
}

// AddWeightImpact adds value to the "weight_impact" field.
func (_u *ErrorResolutionUpdateOne) AddWeightImpact(v float64) *ErrorResolutionUpdateOne {
	_u.mutation.AddWeightImpact(v)
	return _u
}

// SetIsResolved sets the "is_resolved" field.
func (_u *ErrorResolutionUpdateOne) SetIsResolved(v bool) *ErrorResolutionUpdateOne {
	_u.mutation.SetIsResolved(v)
	return _u
}

// SetNillableIsResolved sets the "is_resolved" field if the given value is not nil.
func (_u *ErrorResolutionUpdateOne) SetNillableIsResolved(v *bool) *ErrorResolutionUpdateOne {
	if v != nil {
		_u.SetIsResolved(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ErrorResolutionUpdateOne) SetCreatedAt(v time.Time) *ErrorResolutionUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ErrorResolutionUpdateOne) SetNillableCreatedAt(v *time.Time) *ErrorResolutionUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetResolvedAt sets the "resolved_at" field.
func (_u *ErrorResolutionUpdateOne) SetResolvedAt(v time.Time) *ErrorResolutionUpdateOne {
	_u.mutation.SetResolvedAt(v)
	return _u
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_u *ErrorResolutionUpdateOne) SetNillableResolvedAt(v *time.Time) *ErrorResolutionUpdateOne {
	if v != nil {
		_u.SetResolvedAt(*v)
	}
	return _u
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (_u *ErrorResolutionUpdateOne) ClearResolvedAt() *ErrorResolutionUpdateOne {
	_u.mutation.ClearResolvedAt()
	return _u
}

// SetNode sets the "node" edge to the Node entity.
func (_u *ErrorResolutionUpdateOne) SetNode(v *Node) *ErrorResolutionUpdateOne {
	return _u.SetNodeID(v.ID)
}

// Mutation returns the ErrorResolutionMutation object of the builder.
func (_u *ErrorResolutionUpdateOne) Mutation() *ErrorResolutionMutation {
	return _u.mutation
}

// ClearNode clears the "node" edge to the Node entity.
func (_u *ErrorResolutionUpdateOne) ClearNode() *ErrorResolutionUpdateOne {
	_u.mutation.ClearNode()
	return _u
}

// Where appends a list predicates to the ErrorResolutionUpdate builder.
func (_u *ErrorResolutionUpdateOne) Where(ps ...predicate.ErrorResolution) *ErrorResolutionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ErrorResolutionUpdateOne) Select(field string, fields ...string) *ErrorResolutionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ErrorResolution entity.
func (_u *ErrorResolutionUpdateOne) Save(ctx context.Context) (*ErrorResolution, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ErrorResolutionUpdateOne) SaveX(ctx context.Context) *ErrorResolution {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ErrorResolutionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ErrorResolutionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ErrorResolutionUpdateOne) check() error {
	if v, ok := _u.mutation.ErrorType(); ok {
		if err := errorresolution.ErrorTypeValidator(v); err != nil {
			return &ValidationError{Name: "error_type", err: fmt.Errorf(`ent: validator failed for field "ErrorResolution.error_type": %w`, err)}
		}
	}
	if _u.mutation.NodeCleared() && len(_u.mutation.NodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ErrorResolution.node"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ErrorResolutionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ErrorResolutionUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ErrorResolutionUpdateOne) sqlSave(ctx context.Context) (_node *ErrorResolution, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(errorresolution.Table, errorresolution.Columns, sqlgraph.NewFieldSpec(errorresolution.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ErrorResolution.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, errorresolution.FieldID)
		for _, f := range fields {
			if !errorresolution.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != errorresolution.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ErrorType(); ok {
		_spec.SetField(errorresolution.FieldErrorType, field.TypeString, value)
	}
	if value, ok := _u.mutation.WeightImpact(); ok {
		_spec.SetField(errorresolution.FieldWeightImpact, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeightImpact(); ok {
		_spec.AddField(errorresolution.FieldWeightImpact, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.IsResolved(); ok {
		_spec.SetField(errorresolution.FieldIsResolved, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(errorresolution.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ResolvedAt(); ok {
		_spec.SetField(errorresolution.FieldResolvedAt, field.TypeTime, value)
	}
	if _u.mutation.ResolvedAtCleared() {
		_spec.ClearField(errorresolution.FieldResolvedAt, field.TypeTime)
	}
	if _u.mutation.NodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   errorresolution.NodeTable,
			Columns: []string{errorresolution.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   errorresolution.NodeTable,
			Columns: []string{errorresolution.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ErrorResolution{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{errorresolution.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
