// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"profen/internal/data/ent/errordefinition"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ErrorDefinition is the model entity for the ErrorDefinition schema.
type ErrorDefinition struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Label holds the value of the "label" field.
	Label string `json:"label,omitempty"`
	// BaseWeight holds the value of the "base_weight" field.
	BaseWeight float64 `json:"base_weight,omitempty"`
	// IsSystem holds the value of the "is_system" field.
	IsSystem bool `json:"is_system,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ErrorDefinitionQuery when eager-loading is set.
	Edges        ErrorDefinitionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ErrorDefinitionEdges holds the relations/edges for other nodes in the graph.
type ErrorDefinitionEdges struct {
	// Attempts holds the value of the attempts edge.
	Attempts []*Attempt `json:"attempts,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AttemptsOrErr returns the Attempts value or an error if the edge
// was not loaded in eager-loading.
func (e ErrorDefinitionEdges) AttemptsOrErr() ([]*Attempt, error) {
	if e.loadedTypes[0] {
		return e.Attempts, nil
	}
	return nil, &NotLoadedError{edge: "attempts"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ErrorDefinition) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case errordefinition.FieldIsSystem:
			values[i] = new(sql.NullBool)
		case errordefinition.FieldBaseWeight:
			values[i] = new(sql.NullFloat64)
		case errordefinition.FieldLabel:
			values[i] = new(sql.NullString)
		case errordefinition.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ErrorDefinition fields.
func (_m *ErrorDefinition) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case errordefinition.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case errordefinition.FieldLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field label", values[i])
			} else if value.Valid {
				_m.Label = value.String
			}
		case errordefinition.FieldBaseWeight:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field base_weight", values[i])
			} else if value.Valid {
				_m.BaseWeight = value.Float64
			}
		case errordefinition.FieldIsSystem:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_system", values[i])
			} else if value.Valid {
				_m.IsSystem = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ErrorDefinition.
// This includes values selected through modifiers, order, etc.
func (_m *ErrorDefinition) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAttempts queries the "attempts" edge of the ErrorDefinition entity.
func (_m *ErrorDefinition) QueryAttempts() *AttemptQuery {
	return NewErrorDefinitionClient(_m.config).QueryAttempts(_m)
}

// Update returns a builder for updating this ErrorDefinition.
// Note that you need to call ErrorDefinition.Unwrap() before calling this method if this ErrorDefinition
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ErrorDefinition) Update() *ErrorDefinitionUpdateOne {
	return NewErrorDefinitionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ErrorDefinition entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ErrorDefinition) Unwrap() *ErrorDefinition {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ErrorDefinition is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ErrorDefinition) String() string {
	var builder strings.Builder
	builder.WriteString("ErrorDefinition(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("label=")
	builder.WriteString(_m.Label)
	builder.WriteString(", ")
	builder.WriteString("base_weight=")
	builder.WriteString(fmt.Sprintf("%v", _m.BaseWeight))
	builder.WriteString(", ")
	builder.WriteString("is_system=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsSystem))
	builder.WriteByte(')')
	return builder.String()
}

// ErrorDefinitions is a parsable slice of ErrorDefinition.
type ErrorDefinitions []*ErrorDefinition
