// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"profen/internal/data/ent/errorresolution"
	"profen/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ErrorResolutionUpdate is the builder for updating ErrorResolution entities.
type ErrorResolutionUpdate struct {
	config
	hooks    []Hook
	mutation *ErrorResolutionMutation
}

// Where appends a list predicates to the ErrorResolutionUpdate builder.
func (_u *ErrorResolutionUpdate) Where(ps ...predicate.ErrorResolution) *ErrorResolutionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the ErrorResolutionMutation object of the builder.
func (_u *ErrorResolutionUpdate) Mutation() *ErrorResolutionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ErrorResolutionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ErrorResolutionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ErrorResolutionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ErrorResolutionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ErrorResolutionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(errorresolution.Table, errorresolution.Columns, sqlgraph.NewFieldSpec(errorresolution.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{errorresolution.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ErrorResolutionUpdateOne is the builder for updating a single ErrorResolution entity.
type ErrorResolutionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ErrorResolutionMutation
}

// Mutation returns the ErrorResolutionMutation object of the builder.
func (_u *ErrorResolutionUpdateOne) Mutation() *ErrorResolutionMutation {
	return _u.mutation
}

// Where appends a list predicates to the ErrorResolutionUpdate builder.
func (_u *ErrorResolutionUpdateOne) Where(ps ...predicate.ErrorResolution) *ErrorResolutionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ErrorResolutionUpdateOne) Select(field string, fields ...string) *ErrorResolutionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ErrorResolution entity.
func (_u *ErrorResolutionUpdateOne) Save(ctx context.Context) (*ErrorResolution, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ErrorResolutionUpdateOne) SaveX(ctx context.Context) *ErrorResolution {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ErrorResolutionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ErrorResolutionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ErrorResolutionUpdateOne) sqlSave(ctx context.Context) (_node *ErrorResolution, err error) {
	_spec := sqlgraph.NewUpdateSpec(errorresolution.Table, errorresolution.Columns, sqlgraph.NewFieldSpec(errorresolution.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ErrorResolution.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, errorresolution.FieldID)
		for _, f := range fields {
			if !errorresolution.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != errorresolution.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &ErrorResolution{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{errorresolution.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
