// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"profen/internal/data/ent/errorresolution"
	"profen/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ErrorResolutionDelete is the builder for deleting a ErrorResolution entity.
type ErrorResolutionDelete struct {
	config
	hooks    []Hook
	mutation *ErrorResolutionMutation
}

// Where appends a list predicates to the ErrorResolutionDelete builder.
func (_d *ErrorResolutionDelete) Where(ps ...predicate.ErrorResolution) *ErrorResolutionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ErrorResolutionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ErrorResolutionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ErrorResolutionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(errorresolution.Table, sqlgraph.NewFieldSpec(errorresolution.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ErrorResolutionDeleteOne is the builder for deleting a single ErrorResolution entity.
type ErrorResolutionDeleteOne struct {
	_d *ErrorResolutionDelete
}

// Where appends a list predicates to the ErrorResolutionDelete builder.
func (_d *ErrorResolutionDeleteOne) Where(ps ...predicate.ErrorResolution) *ErrorResolutionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ErrorResolutionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{errorresolution.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ErrorResolutionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
