// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"profen/internal/data/ent/node"
	"profen/internal/data/ent/nodeclosure"
	"profen/internal/data/ent/predicate"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// NodeClosureQuery is the builder for querying NodeClosure entities.
type NodeClosureQuery struct {
	config
	ctx            *QueryContext
	order          []nodeclosure.OrderOption
	inters         []Interceptor
	predicates     []predicate.NodeClosure
	withAncestor   *NodeQuery
	withDescendant *NodeQuery
	modifiers      []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the NodeClosureQuery builder.
func (_q *NodeClosureQuery) Where(ps ...predicate.NodeClosure) *NodeClosureQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *NodeClosureQuery) Limit(limit int) *NodeClosureQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *NodeClosureQuery) Offset(offset int) *NodeClosureQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *NodeClosureQuery) Unique(unique bool) *NodeClosureQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *NodeClosureQuery) Order(o ...nodeclosure.OrderOption) *NodeClosureQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryAncestor chains the current query on the "ancestor" edge.
func (_q *NodeClosureQuery) QueryAncestor() *NodeQuery {
	query := (&NodeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(nodeclosure.Table, nodeclosure.FieldID, selector),
			sqlgraph.To(node.Table, node.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, nodeclosure.AncestorTable, nodeclosure.AncestorColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDescendant chains the current query on the "descendant" edge.
func (_q *NodeClosureQuery) QueryDescendant() *NodeQuery {
	query := (&NodeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(nodeclosure.Table, nodeclosure.FieldID, selector),
			sqlgraph.To(node.Table, node.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, nodeclosure.DescendantTable, nodeclosure.DescendantColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first NodeClosure entity from the query.
// Returns a *NotFoundError when no NodeClosure was found.
func (_q *NodeClosureQuery) First(ctx context.Context) (*NodeClosure, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{nodeclosure.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *NodeClosureQuery) FirstX(ctx context.Context) *NodeClosure {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first NodeClosure ID from the query.
// Returns a *NotFoundError when no NodeClosure ID was found.
func (_q *NodeClosureQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{nodeclosure.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *NodeClosureQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single NodeClosure entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one NodeClosure entity is found.
// Returns a *NotFoundError when no NodeClosure entities are found.
func (_q *NodeClosureQuery) Only(ctx context.Context) (*NodeClosure, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{nodeclosure.Label}
	default:
		return nil, &NotSingularError{nodeclosure.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *NodeClosureQuery) OnlyX(ctx context.Context) *NodeClosure {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only NodeClosure ID in the query.
// Returns a *NotSingularError when more than one NodeClosure ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *NodeClosureQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{nodeclosure.Label}
	default:
		err = &NotSingularError{nodeclosure.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *NodeClosureQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of NodeClosures.
func (_q *NodeClosureQuery) All(ctx context.Context) ([]*NodeClosure, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*NodeClosure, *NodeClosureQuery]()
	return withInterceptors[[]*NodeClosure](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *NodeClosureQuery) AllX(ctx context.Context) []*NodeClosure {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of NodeClosure IDs.
func (_q *NodeClosureQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(nodeclosure.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *NodeClosureQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *NodeClosureQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*NodeClosureQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *NodeClosureQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *NodeClosureQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *NodeClosureQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the NodeClosureQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *NodeClosureQuery) Clone() *NodeClosureQuery {
	if _q == nil {
		return nil
	}
	return &NodeClosureQuery{
		config:         _q.config,
		ctx:            _q.ctx.Clone(),
		order:          append([]nodeclosure.OrderOption{}, _q.order...),
		inters:         append([]Interceptor{}, _q.inters...),
		predicates:     append([]predicate.NodeClosure{}, _q.predicates...),
		withAncestor:   _q.withAncestor.Clone(),
		withDescendant: _q.withDescendant.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithAncestor tells the query-builder to eager-load the nodes that are connected to
// the "ancestor" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *NodeClosureQuery) WithAncestor(opts ...func(*NodeQuery)) *NodeClosureQuery {
	query := (&NodeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAncestor = query
	return _q
}

// WithDescendant tells the query-builder to eager-load the nodes that are connected to
// the "descendant" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *NodeClosureQuery) WithDescendant(opts ...func(*NodeQuery)) *NodeClosureQuery {
	query := (&NodeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDescendant = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AncestorID uuid.UUID `json:"ancestor_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.NodeClosure.Query().
//		GroupBy(nodeclosure.FieldAncestorID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *NodeClosureQuery) GroupBy(field string, fields ...string) *NodeClosureGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &NodeClosureGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = nodeclosure.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AncestorID uuid.UUID `json:"ancestor_id,omitempty"`
//	}
//
//	client.NodeClosure.Query().
//		Select(nodeclosure.FieldAncestorID).
//		Scan(ctx, &v)
func (_q *NodeClosureQuery) Select(fields ...string) *NodeClosureSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &NodeClosureSelect{NodeClosureQuery: _q}
	sbuild.label = nodeclosure.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a NodeClosureSelect configured with the given aggregations.
func (_q *NodeClosureQuery) Aggregate(fns ...AggregateFunc) *NodeClosureSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *NodeClosureQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !nodeclosure.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *NodeClosureQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*NodeClosure, error) {
	var (
		nodes       = []*NodeClosure{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withAncestor != nil,
			_q.withDescendant != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*NodeClosure).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &NodeClosure{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withAncestor; query != nil {
		if err := _q.loadAncestor(ctx, query, nodes, nil,
			func(n *NodeClosure, e *Node) { n.Edges.Ancestor = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDescendant; query != nil {
		if err := _q.loadDescendant(ctx, query, nodes, nil,
			func(n *NodeClosure, e *Node) { n.Edges.Descendant = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *NodeClosureQuery) loadAncestor(ctx context.Context, query *NodeQuery, nodes []*NodeClosure, init func(*NodeClosure), assign func(*NodeClosure, *Node)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*NodeClosure)
	for i := range nodes {
		fk := nodes[i].AncestorID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(node.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "ancestor_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *NodeClosureQuery) loadDescendant(ctx context.Context, query *NodeQuery, nodes []*NodeClosure, init func(*NodeClosure), assign func(*NodeClosure, *Node)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*NodeClosure)
	for i := range nodes {
		fk := nodes[i].DescendantID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(node.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "descendant_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *NodeClosureQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *NodeClosureQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(nodeclosure.Table, nodeclosure.Columns, sqlgraph.NewFieldSpec(nodeclosure.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, nodeclosure.FieldID)
		for i := range fields {
			if fields[i] != nodeclosure.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withAncestor != nil {
			_spec.Node.AddColumnOnce(nodeclosure.FieldAncestorID)
		}
		if _q.withDescendant != nil {
			_spec.Node.AddColumnOnce(nodeclosure.FieldDescendantID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *NodeClosureQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(nodeclosure.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = nodeclosure.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *NodeClosureQuery) Modify(modifiers ...func(s *sql.Selector)) *NodeClosureSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// NodeClosureGroupBy is the group-by builder for NodeClosure entities.
type NodeClosureGroupBy struct {
	selector
	build *NodeClosureQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *NodeClosureGroupBy) Aggregate(fns ...AggregateFunc) *NodeClosureGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *NodeClosureGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NodeClosureQuery, *NodeClosureGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *NodeClosureGroupBy) sqlScan(ctx context.Context, root *NodeClosureQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// NodeClosureSelect is the builder for selecting fields of NodeClosure entities.
type NodeClosureSelect struct {
	*NodeClosureQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *NodeClosureSelect) Aggregate(fns ...AggregateFunc) *NodeClosureSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *NodeClosureSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NodeClosureQuery, *NodeClosureSelect](ctx, _s.NodeClosureQuery, _s, _s.inters, v)
}

func (_s *NodeClosureSelect) sqlScan(ctx context.Context, root *NodeClosureQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *NodeClosureSelect) Modify(modifiers ...func(s *sql.Selector)) *NodeClosureSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
