// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"profen/internal/data/ent/node"
	"profen/internal/data/ent/nodeclosure"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// NodeClosureCreate is the builder for creating a NodeClosure entity.
type NodeClosureCreate struct {
	config
	mutation *NodeClosureMutation
	hooks    []Hook
}

// SetAncestorID sets the "ancestor_id" field.
func (_c *NodeClosureCreate) SetAncestorID(v uuid.UUID) *NodeClosureCreate {
	_c.mutation.SetAncestorID(v)
	return _c
}

// SetDescendantID sets the "descendant_id" field.
func (_c *NodeClosureCreate) SetDescendantID(v uuid.UUID) *NodeClosureCreate {
	_c.mutation.SetDescendantID(v)
	return _c
}

// SetDepth sets the "depth" field.
func (_c *NodeClosureCreate) SetDepth(v int) *NodeClosureCreate {
	_c.mutation.SetDepth(v)
	return _c
}

// SetAncestor sets the "ancestor" edge to the Node entity.
func (_c *NodeClosureCreate) SetAncestor(v *Node) *NodeClosureCreate {
	return _c.SetAncestorID(v.ID)
}

// SetDescendant sets the "descendant" edge to the Node entity.
func (_c *NodeClosureCreate) SetDescendant(v *Node) *NodeClosureCreate {
	return _c.SetDescendantID(v.ID)
}

// Mutation returns the NodeClosureMutation object of the builder.
func (_c *NodeClosureCreate) Mutation() *NodeClosureMutation {
	return _c.mutation
}

// Save creates the NodeClosure in the database.
func (_c *NodeClosureCreate) Save(ctx context.Context) (*NodeClosure, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NodeClosureCreate) SaveX(ctx context.Context) *NodeClosure {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NodeClosureCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NodeClosureCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NodeClosureCreate) check() error {
	if _, ok := _c.mutation.AncestorID(); !ok {
		return &ValidationError{Name: "ancestor_id", err: errors.New(`ent: missing required field "NodeClosure.ancestor_id"`)}
	}
	if _, ok := _c.mutation.DescendantID(); !ok {
		return &ValidationError{Name: "descendant_id", err: errors.New(`ent: missing required field "NodeClosure.descendant_id"`)}
	}
	if _, ok := _c.mutation.Depth(); !ok {
		return &ValidationError{Name: "depth", err: errors.New(`ent: missing required field "NodeClosure.depth"`)}
	}
	if len(_c.mutation.AncestorIDs()) == 0 {
		return &ValidationError{Name: "ancestor", err: errors.New(`ent: missing required edge "NodeClosure.ancestor"`)}
	}
	if len(_c.mutation.DescendantIDs()) == 0 {
		return &ValidationError{Name: "descendant", err: errors.New(`ent: missing required edge "NodeClosure.descendant"`)}
	}
	return nil
}

func (_c *NodeClosureCreate) sqlSave(ctx context.Context) (*NodeClosure, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NodeClosureCreate) createSpec() (*NodeClosure, *sqlgraph.CreateSpec) {
	var (
		_node = &NodeClosure{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(nodeclosure.Table, sqlgraph.NewFieldSpec(nodeclosure.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Depth(); ok {
		_spec.SetField(nodeclosure.FieldDepth, field.TypeInt, value)
		_node.Depth = value
	}
	if nodes := _c.mutation.AncestorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   nodeclosure.AncestorTable,
			Columns: []string{nodeclosure.AncestorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AncestorID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DescendantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   nodeclosure.DescendantTable,
			Columns: []string{nodeclosure.DescendantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DescendantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// NodeClosureCreateBulk is the builder for creating many NodeClosure entities in bulk.
type NodeClosureCreateBulk struct {
	config
	err      error
	builders []*NodeClosureCreate
}

// Save creates the NodeClosure entities in the database.
func (_c *NodeClosureCreateBulk) Save(ctx context.Context) ([]*NodeClosure, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NodeClosure, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NodeClosureMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NodeClosureCreateBulk) SaveX(ctx context.Context) []*NodeClosure {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NodeClosureCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NodeClosureCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
