// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"profen/internal/data/ent/fsrscard"
	"profen/internal/data/ent/node"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Node is the model entity for the Node schema.
type Node struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Type holds the value of the "type" field.
	Type node.Type `json:"type,omitempty"`
	// Markdown content, LaTeX, code snippets
	Body string `json:"body,omitempty"`
	// Image dimensions, code flags, source URLs
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// ParentID holds the value of the "parent_id" field.
	ParentID *uuid.UUID `json:"parent_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NodeQuery when eager-loading is set.
	Edges        NodeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// NodeEdges holds the relations/edges for other nodes in the graph.
type NodeEdges struct {
	// Parent holds the value of the parent edge.
	Parent *Node `json:"parent,omitempty"`
	// Children holds the value of the children edge.
	Children []*Node `json:"children,omitempty"`
	// ChildClosures holds the value of the child_closures edge.
	ChildClosures []*NodeClosure `json:"child_closures,omitempty"`
	// ParentClosures holds the value of the parent_closures edge.
	ParentClosures []*NodeClosure `json:"parent_closures,omitempty"`
	// OutgoingAssociations holds the value of the outgoing_associations edge.
	OutgoingAssociations []*NodeAssociation `json:"outgoing_associations,omitempty"`
	// IncomingAssociations holds the value of the incoming_associations edge.
	IncomingAssociations []*NodeAssociation `json:"incoming_associations,omitempty"`
	// FsrsCard holds the value of the fsrs_card edge.
	FsrsCard *FsrsCard `json:"fsrs_card,omitempty"`
	// ErrorResolutions holds the value of the error_resolutions edge.
	ErrorResolutions []*ErrorResolution `json:"error_resolutions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [8]bool
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NodeEdges) ParentOrErr() (*Node, error) {
	if e.Parent != nil {
		return e.Parent, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: node.Label}
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// ChildrenOrErr returns the Children value or an error if the edge
// was not loaded in eager-loading.
func (e NodeEdges) ChildrenOrErr() ([]*Node, error) {
	if e.loadedTypes[1] {
		return e.Children, nil
	}
	return nil, &NotLoadedError{edge: "children"}
}

// ChildClosuresOrErr returns the ChildClosures value or an error if the edge
// was not loaded in eager-loading.
func (e NodeEdges) ChildClosuresOrErr() ([]*NodeClosure, error) {
	if e.loadedTypes[2] {
		return e.ChildClosures, nil
	}
	return nil, &NotLoadedError{edge: "child_closures"}
}

// ParentClosuresOrErr returns the ParentClosures value or an error if the edge
// was not loaded in eager-loading.
func (e NodeEdges) ParentClosuresOrErr() ([]*NodeClosure, error) {
	if e.loadedTypes[3] {
		return e.ParentClosures, nil
	}
	return nil, &NotLoadedError{edge: "parent_closures"}
}

// OutgoingAssociationsOrErr returns the OutgoingAssociations value or an error if the edge
// was not loaded in eager-loading.
func (e NodeEdges) OutgoingAssociationsOrErr() ([]*NodeAssociation, error) {
	if e.loadedTypes[4] {
		return e.OutgoingAssociations, nil
	}
	return nil, &NotLoadedError{edge: "outgoing_associations"}
}

// IncomingAssociationsOrErr returns the IncomingAssociations value or an error if the edge
// was not loaded in eager-loading.
func (e NodeEdges) IncomingAssociationsOrErr() ([]*NodeAssociation, error) {
	if e.loadedTypes[5] {
		return e.IncomingAssociations, nil
	}
	return nil, &NotLoadedError{edge: "incoming_associations"}
}

// FsrsCardOrErr returns the FsrsCard value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NodeEdges) FsrsCardOrErr() (*FsrsCard, error) {
	if e.FsrsCard != nil {
		return e.FsrsCard, nil
	} else if e.loadedTypes[6] {
		return nil, &NotFoundError{label: fsrscard.Label}
	}
	return nil, &NotLoadedError{edge: "fsrs_card"}
}

// ErrorResolutionsOrErr returns the ErrorResolutions value or an error if the edge
// was not loaded in eager-loading.
func (e NodeEdges) ErrorResolutionsOrErr() ([]*ErrorResolution, error) {
	if e.loadedTypes[7] {
		return e.ErrorResolutions, nil
	}
	return nil, &NotLoadedError{edge: "error_resolutions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Node) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case node.FieldParentID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case node.FieldMetadata:
			values[i] = new([]byte)
		case node.FieldType, node.FieldBody:
			values[i] = new(sql.NullString)
		case node.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case node.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Node fields.
func (_m *Node) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case node.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case node.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = node.Type(value.String)
			}
		case node.FieldBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field body", values[i])
			} else if value.Valid {
				_m.Body = value.String
			}
		case node.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case node.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case node.FieldParentID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field parent_id", values[i])
			} else if value.Valid {
				_m.ParentID = new(uuid.UUID)
				*_m.ParentID = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Node.
// This includes values selected through modifiers, order, etc.
func (_m *Node) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryParent queries the "parent" edge of the Node entity.
func (_m *Node) QueryParent() *NodeQuery {
	return NewNodeClient(_m.config).QueryParent(_m)
}

// QueryChildren queries the "children" edge of the Node entity.
func (_m *Node) QueryChildren() *NodeQuery {
	return NewNodeClient(_m.config).QueryChildren(_m)
}

// QueryChildClosures queries the "child_closures" edge of the Node entity.
func (_m *Node) QueryChildClosures() *NodeClosureQuery {
	return NewNodeClient(_m.config).QueryChildClosures(_m)
}

// QueryParentClosures queries the "parent_closures" edge of the Node entity.
func (_m *Node) QueryParentClosures() *NodeClosureQuery {
	return NewNodeClient(_m.config).QueryParentClosures(_m)
}

// QueryOutgoingAssociations queries the "outgoing_associations" edge of the Node entity.
func (_m *Node) QueryOutgoingAssociations() *NodeAssociationQuery {
	return NewNodeClient(_m.config).QueryOutgoingAssociations(_m)
}

// QueryIncomingAssociations queries the "incoming_associations" edge of the Node entity.
func (_m *Node) QueryIncomingAssociations() *NodeAssociationQuery {
	return NewNodeClient(_m.config).QueryIncomingAssociations(_m)
}

// QueryFsrsCard queries the "fsrs_card" edge of the Node entity.
func (_m *Node) QueryFsrsCard() *FsrsCardQuery {
	return NewNodeClient(_m.config).QueryFsrsCard(_m)
}

// QueryErrorResolutions queries the "error_resolutions" edge of the Node entity.
func (_m *Node) QueryErrorResolutions() *ErrorResolutionQuery {
	return NewNodeClient(_m.config).QueryErrorResolutions(_m)
}

// Update returns a builder for updating this Node.
// Note that you need to call Node.Unwrap() before calling this method if this Node
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Node) Update() *NodeUpdateOne {
	return NewNodeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Node entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Node) Unwrap() *Node {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Node is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Node) String() string {
	var builder strings.Builder
	builder.WriteString("Node(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("body=")
	builder.WriteString(_m.Body)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ParentID; v != nil {
		builder.WriteString("parent_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Nodes is a parsable slice of Node.
type Nodes []*Node
