// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"profen/internal/data/ent/node"
	"profen/internal/data/ent/nodeassociation"
	"profen/internal/data/ent/nodeclosure"
	"profen/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// NodeUpdate is the builder for updating Node entities.
type NodeUpdate struct {
	config
	hooks    []Hook
	mutation *NodeMutation
}

// Where appends a list predicates to the NodeUpdate builder.
func (_u *NodeUpdate) Where(ps ...predicate.Node) *NodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetType sets the "type" field.
func (_u *NodeUpdate) SetType(v node.Type) *NodeUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableType(v *node.Type) *NodeUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *NodeUpdate) SetBody(v string) *NodeUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableBody(v *string) *NodeUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// ClearBody clears the value of the "body" field.
func (_u *NodeUpdate) ClearBody() *NodeUpdate {
	_u.mutation.ClearBody()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *NodeUpdate) SetMetadata(v map[string]interface{}) *NodeUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *NodeUpdate) ClearMetadata() *NodeUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *NodeUpdate) SetParentID(v uuid.UUID) *NodeUpdate {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableParentID(v *uuid.UUID) *NodeUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *NodeUpdate) ClearParentID() *NodeUpdate {
	_u.mutation.ClearParentID()
	return _u
}

// SetParent sets the "parent" edge to the Node entity.
func (_u *NodeUpdate) SetParent(v *Node) *NodeUpdate {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Node entity by IDs.
func (_u *NodeUpdate) AddChildIDs(ids ...uuid.UUID) *NodeUpdate {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Node entity.
func (_u *NodeUpdate) AddChildren(v ...*Node) *NodeUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// AddChildClosureIDs adds the "child_closures" edge to the NodeClosure entity by IDs.
func (_u *NodeUpdate) AddChildClosureIDs(ids ...int) *NodeUpdate {
	_u.mutation.AddChildClosureIDs(ids...)
	return _u
}

// AddChildClosures adds the "child_closures" edges to the NodeClosure entity.
func (_u *NodeUpdate) AddChildClosures(v ...*NodeClosure) *NodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildClosureIDs(ids...)
}

// AddParentClosureIDs adds the "parent_closures" edge to the NodeClosure entity by IDs.
func (_u *NodeUpdate) AddParentClosureIDs(ids ...int) *NodeUpdate {
	_u.mutation.AddParentClosureIDs(ids...)
	return _u
}

// AddParentClosures adds the "parent_closures" edges to the NodeClosure entity.
func (_u *NodeUpdate) AddParentClosures(v ...*NodeClosure) *NodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddParentClosureIDs(ids...)
}

// AddOutgoingAssociationIDs adds the "outgoing_associations" edge to the NodeAssociation entity by IDs.
func (_u *NodeUpdate) AddOutgoingAssociationIDs(ids ...int) *NodeUpdate {
	_u.mutation.AddOutgoingAssociationIDs(ids...)
	return _u
}

// AddOutgoingAssociations adds the "outgoing_associations" edges to the NodeAssociation entity.
func (_u *NodeUpdate) AddOutgoingAssociations(v ...*NodeAssociation) *NodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOutgoingAssociationIDs(ids...)
}

// AddIncomingAssociationIDs adds the "incoming_associations" edge to the NodeAssociation entity by IDs.
func (_u *NodeUpdate) AddIncomingAssociationIDs(ids ...int) *NodeUpdate {
	_u.mutation.AddIncomingAssociationIDs(ids...)
	return _u
}

// AddIncomingAssociations adds the "incoming_associations" edges to the NodeAssociation entity.
func (_u *NodeUpdate) AddIncomingAssociations(v ...*NodeAssociation) *NodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddIncomingAssociationIDs(ids...)
}

// Mutation returns the NodeMutation object of the builder.
func (_u *NodeUpdate) Mutation() *NodeMutation {
	return _u.mutation
}

// ClearParent clears the "parent" edge to the Node entity.
func (_u *NodeUpdate) ClearParent() *NodeUpdate {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the Node entity.
func (_u *NodeUpdate) ClearChildren() *NodeUpdate {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Node entities by IDs.
func (_u *NodeUpdate) RemoveChildIDs(ids ...uuid.UUID) *NodeUpdate {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Node entities.
func (_u *NodeUpdate) RemoveChildren(v ...*Node) *NodeUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearChildClosures clears all "child_closures" edges to the NodeClosure entity.
func (_u *NodeUpdate) ClearChildClosures() *NodeUpdate {
	_u.mutation.ClearChildClosures()
	return _u
}

// RemoveChildClosureIDs removes the "child_closures" edge to NodeClosure entities by IDs.
func (_u *NodeUpdate) RemoveChildClosureIDs(ids ...int) *NodeUpdate {
	_u.mutation.RemoveChildClosureIDs(ids...)
	return _u
}

// RemoveChildClosures removes "child_closures" edges to NodeClosure entities.
func (_u *NodeUpdate) RemoveChildClosures(v ...*NodeClosure) *NodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildClosureIDs(ids...)
}

// ClearParentClosures clears all "parent_closures" edges to the NodeClosure entity.
func (_u *NodeUpdate) ClearParentClosures() *NodeUpdate {
	_u.mutation.ClearParentClosures()
	return _u
}

// RemoveParentClosureIDs removes the "parent_closures" edge to NodeClosure entities by IDs.
func (_u *NodeUpdate) RemoveParentClosureIDs(ids ...int) *NodeUpdate {
	_u.mutation.RemoveParentClosureIDs(ids...)
	return _u
}

// RemoveParentClosures removes "parent_closures" edges to NodeClosure entities.
func (_u *NodeUpdate) RemoveParentClosures(v ...*NodeClosure) *NodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveParentClosureIDs(ids...)
}

// ClearOutgoingAssociations clears all "outgoing_associations" edges to the NodeAssociation entity.
func (_u *NodeUpdate) ClearOutgoingAssociations() *NodeUpdate {
	_u.mutation.ClearOutgoingAssociations()
	return _u
}

// RemoveOutgoingAssociationIDs removes the "outgoing_associations" edge to NodeAssociation entities by IDs.
func (_u *NodeUpdate) RemoveOutgoingAssociationIDs(ids ...int) *NodeUpdate {
	_u.mutation.RemoveOutgoingAssociationIDs(ids...)
	return _u
}

// RemoveOutgoingAssociations removes "outgoing_associations" edges to NodeAssociation entities.
func (_u *NodeUpdate) RemoveOutgoingAssociations(v ...*NodeAssociation) *NodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOutgoingAssociationIDs(ids...)
}

// ClearIncomingAssociations clears all "incoming_associations" edges to the NodeAssociation entity.
func (_u *NodeUpdate) ClearIncomingAssociations() *NodeUpdate {
	_u.mutation.ClearIncomingAssociations()
	return _u
}

// RemoveIncomingAssociationIDs removes the "incoming_associations" edge to NodeAssociation entities by IDs.
func (_u *NodeUpdate) RemoveIncomingAssociationIDs(ids ...int) *NodeUpdate {
	_u.mutation.RemoveIncomingAssociationIDs(ids...)
	return _u
}

// RemoveIncomingAssociations removes "incoming_associations" edges to NodeAssociation entities.
func (_u *NodeUpdate) RemoveIncomingAssociations(v ...*NodeAssociation) *NodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveIncomingAssociationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NodeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NodeUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := node.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Node.type": %w`, err)}
		}
	}
	return nil
}

func (_u *NodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(node.Table, node.Columns, sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(node.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(node.FieldBody, field.TypeString, value)
	}
	if _u.mutation.BodyCleared() {
		_spec.ClearField(node.FieldBody, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(node.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(node.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   node.ParentTable,
			Columns: []string{node.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   node.ParentTable,
			Columns: []string{node.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.ChildrenTable,
			Columns: []string{node.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.ChildrenTable,
			Columns: []string{node.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.ChildrenTable,
			Columns: []string{node.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildClosuresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.ChildClosuresTable,
			Columns: []string{node.ChildClosuresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeclosure.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildClosuresIDs(); len(nodes) > 0 && !_u.mutation.ChildClosuresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.ChildClosuresTable,
			Columns: []string{node.ChildClosuresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeclosure.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildClosuresIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.ChildClosuresTable,
			Columns: []string{node.ChildClosuresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeclosure.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentClosuresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.ParentClosuresTable,
			Columns: []string{node.ParentClosuresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeclosure.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedParentClosuresIDs(); len(nodes) > 0 && !_u.mutation.ParentClosuresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.ParentClosuresTable,
			Columns: []string{node.ParentClosuresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeclosure.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentClosuresIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.ParentClosuresTable,
			Columns: []string{node.ParentClosuresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeclosure.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OutgoingAssociationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.OutgoingAssociationsTable,
			Columns: []string{node.OutgoingAssociationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeassociation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOutgoingAssociationsIDs(); len(nodes) > 0 && !_u.mutation.OutgoingAssociationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.OutgoingAssociationsTable,
			Columns: []string{node.OutgoingAssociationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeassociation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OutgoingAssociationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.OutgoingAssociationsTable,
			Columns: []string{node.OutgoingAssociationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeassociation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.IncomingAssociationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.IncomingAssociationsTable,
			Columns: []string{node.IncomingAssociationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeassociation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedIncomingAssociationsIDs(); len(nodes) > 0 && !_u.mutation.IncomingAssociationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.IncomingAssociationsTable,
			Columns: []string{node.IncomingAssociationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeassociation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IncomingAssociationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.IncomingAssociationsTable,
			Columns: []string{node.IncomingAssociationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeassociation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{node.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NodeUpdateOne is the builder for updating a single Node entity.
type NodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NodeMutation
}

// SetType sets the "type" field.
func (_u *NodeUpdateOne) SetType(v node.Type) *NodeUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableType(v *node.Type) *NodeUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *NodeUpdateOne) SetBody(v string) *NodeUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableBody(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// ClearBody clears the value of the "body" field.
func (_u *NodeUpdateOne) ClearBody() *NodeUpdateOne {
	_u.mutation.ClearBody()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *NodeUpdateOne) SetMetadata(v map[string]interface{}) *NodeUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *NodeUpdateOne) ClearMetadata() *NodeUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *NodeUpdateOne) SetParentID(v uuid.UUID) *NodeUpdateOne {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableParentID(v *uuid.UUID) *NodeUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *NodeUpdateOne) ClearParentID() *NodeUpdateOne {
	_u.mutation.ClearParentID()
	return _u
}

// SetParent sets the "parent" edge to the Node entity.
func (_u *NodeUpdateOne) SetParent(v *Node) *NodeUpdateOne {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Node entity by IDs.
func (_u *NodeUpdateOne) AddChildIDs(ids ...uuid.UUID) *NodeUpdateOne {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Node entity.
func (_u *NodeUpdateOne) AddChildren(v ...*Node) *NodeUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// AddChildClosureIDs adds the "child_closures" edge to the NodeClosure entity by IDs.
func (_u *NodeUpdateOne) AddChildClosureIDs(ids ...int) *NodeUpdateOne {
	_u.mutation.AddChildClosureIDs(ids...)
	return _u
}

// AddChildClosures adds the "child_closures" edges to the NodeClosure entity.
func (_u *NodeUpdateOne) AddChildClosures(v ...*NodeClosure) *NodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildClosureIDs(ids...)
}

// AddParentClosureIDs adds the "parent_closures" edge to the NodeClosure entity by IDs.
func (_u *NodeUpdateOne) AddParentClosureIDs(ids ...int) *NodeUpdateOne {
	_u.mutation.AddParentClosureIDs(ids...)
	return _u
}

// AddParentClosures adds the "parent_closures" edges to the NodeClosure entity.
func (_u *NodeUpdateOne) AddParentClosures(v ...*NodeClosure) *NodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddParentClosureIDs(ids...)
}

// AddOutgoingAssociationIDs adds the "outgoing_associations" edge to the NodeAssociation entity by IDs.
func (_u *NodeUpdateOne) AddOutgoingAssociationIDs(ids ...int) *NodeUpdateOne {
	_u.mutation.AddOutgoingAssociationIDs(ids...)
	return _u
}

// AddOutgoingAssociations adds the "outgoing_associations" edges to the NodeAssociation entity.
func (_u *NodeUpdateOne) AddOutgoingAssociations(v ...*NodeAssociation) *NodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOutgoingAssociationIDs(ids...)
}

// AddIncomingAssociationIDs adds the "incoming_associations" edge to the NodeAssociation entity by IDs.
func (_u *NodeUpdateOne) AddIncomingAssociationIDs(ids ...int) *NodeUpdateOne {
	_u.mutation.AddIncomingAssociationIDs(ids...)
	return _u
}

// AddIncomingAssociations adds the "incoming_associations" edges to the NodeAssociation entity.
func (_u *NodeUpdateOne) AddIncomingAssociations(v ...*NodeAssociation) *NodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddIncomingAssociationIDs(ids...)
}

// Mutation returns the NodeMutation object of the builder.
func (_u *NodeUpdateOne) Mutation() *NodeMutation {
	return _u.mutation
}

// ClearParent clears the "parent" edge to the Node entity.
func (_u *NodeUpdateOne) ClearParent() *NodeUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the Node entity.
func (_u *NodeUpdateOne) ClearChildren() *NodeUpdateOne {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Node entities by IDs.
func (_u *NodeUpdateOne) RemoveChildIDs(ids ...uuid.UUID) *NodeUpdateOne {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Node entities.
func (_u *NodeUpdateOne) RemoveChildren(v ...*Node) *NodeUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearChildClosures clears all "child_closures" edges to the NodeClosure entity.
func (_u *NodeUpdateOne) ClearChildClosures() *NodeUpdateOne {
	_u.mutation.ClearChildClosures()
	return _u
}

// RemoveChildClosureIDs removes the "child_closures" edge to NodeClosure entities by IDs.
func (_u *NodeUpdateOne) RemoveChildClosureIDs(ids ...int) *NodeUpdateOne {
	_u.mutation.RemoveChildClosureIDs(ids...)
	return _u
}

// RemoveChildClosures removes "child_closures" edges to NodeClosure entities.
func (_u *NodeUpdateOne) RemoveChildClosures(v ...*NodeClosure) *NodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildClosureIDs(ids...)
}

// ClearParentClosures clears all "parent_closures" edges to the NodeClosure entity.
func (_u *NodeUpdateOne) ClearParentClosures() *NodeUpdateOne {
	_u.mutation.ClearParentClosures()
	return _u
}

// RemoveParentClosureIDs removes the "parent_closures" edge to NodeClosure entities by IDs.
func (_u *NodeUpdateOne) RemoveParentClosureIDs(ids ...int) *NodeUpdateOne {
	_u.mutation.RemoveParentClosureIDs(ids...)
	return _u
}

// RemoveParentClosures removes "parent_closures" edges to NodeClosure entities.
func (_u *NodeUpdateOne) RemoveParentClosures(v ...*NodeClosure) *NodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveParentClosureIDs(ids...)
}

// ClearOutgoingAssociations clears all "outgoing_associations" edges to the NodeAssociation entity.
func (_u *NodeUpdateOne) ClearOutgoingAssociations() *NodeUpdateOne {
	_u.mutation.ClearOutgoingAssociations()
	return _u
}

// RemoveOutgoingAssociationIDs removes the "outgoing_associations" edge to NodeAssociation entities by IDs.
func (_u *NodeUpdateOne) RemoveOutgoingAssociationIDs(ids ...int) *NodeUpdateOne {
	_u.mutation.RemoveOutgoingAssociationIDs(ids...)
	return _u
}

// RemoveOutgoingAssociations removes "outgoing_associations" edges to NodeAssociation entities.
func (_u *NodeUpdateOne) RemoveOutgoingAssociations(v ...*NodeAssociation) *NodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOutgoingAssociationIDs(ids...)
}

// ClearIncomingAssociations clears all "incoming_associations" edges to the NodeAssociation entity.
func (_u *NodeUpdateOne) ClearIncomingAssociations() *NodeUpdateOne {
	_u.mutation.ClearIncomingAssociations()
	return _u
}

// RemoveIncomingAssociationIDs removes the "incoming_associations" edge to NodeAssociation entities by IDs.
func (_u *NodeUpdateOne) RemoveIncomingAssociationIDs(ids ...int) *NodeUpdateOne {
	_u.mutation.RemoveIncomingAssociationIDs(ids...)
	return _u
}

// RemoveIncomingAssociations removes "incoming_associations" edges to NodeAssociation entities.
func (_u *NodeUpdateOne) RemoveIncomingAssociations(v ...*NodeAssociation) *NodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveIncomingAssociationIDs(ids...)
}

// Where appends a list predicates to the NodeUpdate builder.
func (_u *NodeUpdateOne) Where(ps ...predicate.Node) *NodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NodeUpdateOne) Select(field string, fields ...string) *NodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Node entity.
func (_u *NodeUpdateOne) Save(ctx context.Context) (*Node, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NodeUpdateOne) SaveX(ctx context.Context) *Node {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NodeUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := node.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Node.type": %w`, err)}
		}
	}
	return nil
}

func (_u *NodeUpdateOne) sqlSave(ctx context.Context) (_node *Node, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(node.Table, node.Columns, sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Node.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, node.FieldID)
		for _, f := range fields {
			if !node.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != node.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(node.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(node.FieldBody, field.TypeString, value)
	}
	if _u.mutation.BodyCleared() {
		_spec.ClearField(node.FieldBody, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(node.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(node.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   node.ParentTable,
			Columns: []string{node.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   node.ParentTable,
			Columns: []string{node.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.ChildrenTable,
			Columns: []string{node.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.ChildrenTable,
			Columns: []string{node.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.ChildrenTable,
			Columns: []string{node.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildClosuresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.ChildClosuresTable,
			Columns: []string{node.ChildClosuresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeclosure.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildClosuresIDs(); len(nodes) > 0 && !_u.mutation.ChildClosuresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.ChildClosuresTable,
			Columns: []string{node.ChildClosuresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeclosure.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildClosuresIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.ChildClosuresTable,
			Columns: []string{node.ChildClosuresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeclosure.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentClosuresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.ParentClosuresTable,
			Columns: []string{node.ParentClosuresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeclosure.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedParentClosuresIDs(); len(nodes) > 0 && !_u.mutation.ParentClosuresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.ParentClosuresTable,
			Columns: []string{node.ParentClosuresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeclosure.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentClosuresIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.ParentClosuresTable,
			Columns: []string{node.ParentClosuresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeclosure.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OutgoingAssociationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.OutgoingAssociationsTable,
			Columns: []string{node.OutgoingAssociationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeassociation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOutgoingAssociationsIDs(); len(nodes) > 0 && !_u.mutation.OutgoingAssociationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.OutgoingAssociationsTable,
			Columns: []string{node.OutgoingAssociationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeassociation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OutgoingAssociationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.OutgoingAssociationsTable,
			Columns: []string{node.OutgoingAssociationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeassociation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.IncomingAssociationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.IncomingAssociationsTable,
			Columns: []string{node.IncomingAssociationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeassociation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedIncomingAssociationsIDs(); len(nodes) > 0 && !_u.mutation.IncomingAssociationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.IncomingAssociationsTable,
			Columns: []string{node.IncomingAssociationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeassociation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IncomingAssociationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.IncomingAssociationsTable,
			Columns: []string{node.IncomingAssociationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeassociation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Node{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{node.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
