// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"profen/internal/data/ent/node"
	"profen/internal/data/ent/nodeassociation"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// NodeAssociation is the model entity for the NodeAssociation schema.
type NodeAssociation struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// SourceID holds the value of the "source_id" field.
	SourceID uuid.UUID `json:"source_id,omitempty"`
	// TargetID holds the value of the "target_id" field.
	TargetID uuid.UUID `json:"target_id,omitempty"`
	// RelType holds the value of the "rel_type" field.
	RelType nodeassociation.RelType `json:"rel_type,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NodeAssociationQuery when eager-loading is set.
	Edges        NodeAssociationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// NodeAssociationEdges holds the relations/edges for other nodes in the graph.
type NodeAssociationEdges struct {
	// Source holds the value of the source edge.
	Source *Node `json:"source,omitempty"`
	// Target holds the value of the target edge.
	Target *Node `json:"target,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// SourceOrErr returns the Source value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NodeAssociationEdges) SourceOrErr() (*Node, error) {
	if e.Source != nil {
		return e.Source, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: node.Label}
	}
	return nil, &NotLoadedError{edge: "source"}
}

// TargetOrErr returns the Target value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NodeAssociationEdges) TargetOrErr() (*Node, error) {
	if e.Target != nil {
		return e.Target, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: node.Label}
	}
	return nil, &NotLoadedError{edge: "target"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NodeAssociation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case nodeassociation.FieldID:
			values[i] = new(sql.NullInt64)
		case nodeassociation.FieldRelType:
			values[i] = new(sql.NullString)
		case nodeassociation.FieldSourceID, nodeassociation.FieldTargetID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NodeAssociation fields.
func (_m *NodeAssociation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case nodeassociation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case nodeassociation.FieldSourceID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field source_id", values[i])
			} else if value != nil {
				_m.SourceID = *value
			}
		case nodeassociation.FieldTargetID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field target_id", values[i])
			} else if value != nil {
				_m.TargetID = *value
			}
		case nodeassociation.FieldRelType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rel_type", values[i])
			} else if value.Valid {
				_m.RelType = nodeassociation.RelType(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NodeAssociation.
// This includes values selected through modifiers, order, etc.
func (_m *NodeAssociation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySource queries the "source" edge of the NodeAssociation entity.
func (_m *NodeAssociation) QuerySource() *NodeQuery {
	return NewNodeAssociationClient(_m.config).QuerySource(_m)
}

// QueryTarget queries the "target" edge of the NodeAssociation entity.
func (_m *NodeAssociation) QueryTarget() *NodeQuery {
	return NewNodeAssociationClient(_m.config).QueryTarget(_m)
}

// Update returns a builder for updating this NodeAssociation.
// Note that you need to call NodeAssociation.Unwrap() before calling this method if this NodeAssociation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *NodeAssociation) Update() *NodeAssociationUpdateOne {
	return NewNodeAssociationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the NodeAssociation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *NodeAssociation) Unwrap() *NodeAssociation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: NodeAssociation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *NodeAssociation) String() string {
	var builder strings.Builder
	builder.WriteString("NodeAssociation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("source_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceID))
	builder.WriteString(", ")
	builder.WriteString("target_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetID))
	builder.WriteString(", ")
	builder.WriteString("rel_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.RelType))
	builder.WriteByte(')')
	return builder.String()
}

// NodeAssociations is a parsable slice of NodeAssociation.
type NodeAssociations []*NodeAssociation
