// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"profen/internal/data/ent/node"
	"profen/internal/data/ent/nodeassociation"
	"profen/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// NodeAssociationUpdate is the builder for updating NodeAssociation entities.
type NodeAssociationUpdate struct {
	config
	hooks    []Hook
	mutation *NodeAssociationMutation
}

// Where appends a list predicates to the NodeAssociationUpdate builder.
func (_u *NodeAssociationUpdate) Where(ps ...predicate.NodeAssociation) *NodeAssociationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *NodeAssociationUpdate) SetSourceID(v uuid.UUID) *NodeAssociationUpdate {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *NodeAssociationUpdate) SetNillableSourceID(v *uuid.UUID) *NodeAssociationUpdate {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *NodeAssociationUpdate) SetTargetID(v uuid.UUID) *NodeAssociationUpdate {
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *NodeAssociationUpdate) SetNillableTargetID(v *uuid.UUID) *NodeAssociationUpdate {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// SetRelType sets the "rel_type" field.
func (_u *NodeAssociationUpdate) SetRelType(v nodeassociation.RelType) *NodeAssociationUpdate {
	_u.mutation.SetRelType(v)
	return _u
}

// SetNillableRelType sets the "rel_type" field if the given value is not nil.
func (_u *NodeAssociationUpdate) SetNillableRelType(v *nodeassociation.RelType) *NodeAssociationUpdate {
	if v != nil {
		_u.SetRelType(*v)
	}
	return _u
}

// SetSource sets the "source" edge to the Node entity.
func (_u *NodeAssociationUpdate) SetSource(v *Node) *NodeAssociationUpdate {
	return _u.SetSourceID(v.ID)
}

// SetTarget sets the "target" edge to the Node entity.
func (_u *NodeAssociationUpdate) SetTarget(v *Node) *NodeAssociationUpdate {
	return _u.SetTargetID(v.ID)
}

// Mutation returns the NodeAssociationMutation object of the builder.
func (_u *NodeAssociationUpdate) Mutation() *NodeAssociationMutation {
	return _u.mutation
}

// ClearSource clears the "source" edge to the Node entity.
func (_u *NodeAssociationUpdate) ClearSource() *NodeAssociationUpdate {
	_u.mutation.ClearSource()
	return _u
}

// ClearTarget clears the "target" edge to the Node entity.
func (_u *NodeAssociationUpdate) ClearTarget() *NodeAssociationUpdate {
	_u.mutation.ClearTarget()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NodeAssociationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NodeAssociationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NodeAssociationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NodeAssociationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NodeAssociationUpdate) check() error {
	if v, ok := _u.mutation.RelType(); ok {
		if err := nodeassociation.RelTypeValidator(v); err != nil {
			return &ValidationError{Name: "rel_type", err: fmt.Errorf(`ent: validator failed for field "NodeAssociation.rel_type": %w`, err)}
		}
	}
	if _u.mutation.SourceCleared() && len(_u.mutation.SourceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NodeAssociation.source"`)
	}
	if _u.mutation.TargetCleared() && len(_u.mutation.TargetIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NodeAssociation.target"`)
	}
	return nil
}

func (_u *NodeAssociationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(nodeassociation.Table, nodeassociation.Columns, sqlgraph.NewFieldSpec(nodeassociation.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RelType(); ok {
		_spec.SetField(nodeassociation.FieldRelType, field.TypeEnum, value)
	}
	if _u.mutation.SourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   nodeassociation.SourceTable,
			Columns: []string{nodeassociation.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   nodeassociation.SourceTable,
			Columns: []string{nodeassociation.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TargetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   nodeassociation.TargetTable,
			Columns: []string{nodeassociation.TargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   nodeassociation.TargetTable,
			Columns: []string{nodeassociation.TargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{nodeassociation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NodeAssociationUpdateOne is the builder for updating a single NodeAssociation entity.
type NodeAssociationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NodeAssociationMutation
}

// SetSourceID sets the "source_id" field.
func (_u *NodeAssociationUpdateOne) SetSourceID(v uuid.UUID) *NodeAssociationUpdateOne {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *NodeAssociationUpdateOne) SetNillableSourceID(v *uuid.UUID) *NodeAssociationUpdateOne {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *NodeAssociationUpdateOne) SetTargetID(v uuid.UUID) *NodeAssociationUpdateOne {
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *NodeAssociationUpdateOne) SetNillableTargetID(v *uuid.UUID) *NodeAssociationUpdateOne {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// SetRelType sets the "rel_type" field.
func (_u *NodeAssociationUpdateOne) SetRelType(v nodeassociation.RelType) *NodeAssociationUpdateOne {
	_u.mutation.SetRelType(v)
	return _u
}

// SetNillableRelType sets the "rel_type" field if the given value is not nil.
func (_u *NodeAssociationUpdateOne) SetNillableRelType(v *nodeassociation.RelType) *NodeAssociationUpdateOne {
	if v != nil {
		_u.SetRelType(*v)
	}
	return _u
}

// SetSource sets the "source" edge to the Node entity.
func (_u *NodeAssociationUpdateOne) SetSource(v *Node) *NodeAssociationUpdateOne {
	return _u.SetSourceID(v.ID)
}

// SetTarget sets the "target" edge to the Node entity.
func (_u *NodeAssociationUpdateOne) SetTarget(v *Node) *NodeAssociationUpdateOne {
	return _u.SetTargetID(v.ID)
}

// Mutation returns the NodeAssociationMutation object of the builder.
func (_u *NodeAssociationUpdateOne) Mutation() *NodeAssociationMutation {
	return _u.mutation
}

// ClearSource clears the "source" edge to the Node entity.
func (_u *NodeAssociationUpdateOne) ClearSource() *NodeAssociationUpdateOne {
	_u.mutation.ClearSource()
	return _u
}

// ClearTarget clears the "target" edge to the Node entity.
func (_u *NodeAssociationUpdateOne) ClearTarget() *NodeAssociationUpdateOne {
	_u.mutation.ClearTarget()
	return _u
}

// Where appends a list predicates to the NodeAssociationUpdate builder.
func (_u *NodeAssociationUpdateOne) Where(ps ...predicate.NodeAssociation) *NodeAssociationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NodeAssociationUpdateOne) Select(field string, fields ...string) *NodeAssociationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NodeAssociation entity.
func (_u *NodeAssociationUpdateOne) Save(ctx context.Context) (*NodeAssociation, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NodeAssociationUpdateOne) SaveX(ctx context.Context) *NodeAssociation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NodeAssociationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NodeAssociationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NodeAssociationUpdateOne) check() error {
	if v, ok := _u.mutation.RelType(); ok {
		if err := nodeassociation.RelTypeValidator(v); err != nil {
			return &ValidationError{Name: "rel_type", err: fmt.Errorf(`ent: validator failed for field "NodeAssociation.rel_type": %w`, err)}
		}
	}
	if _u.mutation.SourceCleared() && len(_u.mutation.SourceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NodeAssociation.source"`)
	}
	if _u.mutation.TargetCleared() && len(_u.mutation.TargetIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NodeAssociation.target"`)
	}
	return nil
}

func (_u *NodeAssociationUpdateOne) sqlSave(ctx context.Context) (_node *NodeAssociation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(nodeassociation.Table, nodeassociation.Columns, sqlgraph.NewFieldSpec(nodeassociation.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NodeAssociation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, nodeassociation.FieldID)
		for _, f := range fields {
			if !nodeassociation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != nodeassociation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RelType(); ok {
		_spec.SetField(nodeassociation.FieldRelType, field.TypeEnum, value)
	}
	if _u.mutation.SourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   nodeassociation.SourceTable,
			Columns: []string{nodeassociation.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   nodeassociation.SourceTable,
			Columns: []string{nodeassociation.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TargetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   nodeassociation.TargetTable,
			Columns: []string{nodeassociation.TargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   nodeassociation.TargetTable,
			Columns: []string{nodeassociation.TargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &NodeAssociation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{nodeassociation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
