// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"profen/internal/data/ent/node"
	"profen/internal/data/ent/nodeclosure"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// NodeClosure is the model entity for the NodeClosure schema.
type NodeClosure struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// AncestorID holds the value of the "ancestor_id" field.
	AncestorID uuid.UUID `json:"ancestor_id,omitempty"`
	// DescendantID holds the value of the "descendant_id" field.
	DescendantID uuid.UUID `json:"descendant_id,omitempty"`
	// Distance between ancestor and descendant. 0 for self.
	Depth int `json:"depth,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NodeClosureQuery when eager-loading is set.
	Edges        NodeClosureEdges `json:"edges"`
	selectValues sql.SelectValues
}

// NodeClosureEdges holds the relations/edges for other nodes in the graph.
type NodeClosureEdges struct {
	// Ancestor holds the value of the ancestor edge.
	Ancestor *Node `json:"ancestor,omitempty"`
	// Descendant holds the value of the descendant edge.
	Descendant *Node `json:"descendant,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AncestorOrErr returns the Ancestor value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NodeClosureEdges) AncestorOrErr() (*Node, error) {
	if e.Ancestor != nil {
		return e.Ancestor, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: node.Label}
	}
	return nil, &NotLoadedError{edge: "ancestor"}
}

// DescendantOrErr returns the Descendant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NodeClosureEdges) DescendantOrErr() (*Node, error) {
	if e.Descendant != nil {
		return e.Descendant, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: node.Label}
	}
	return nil, &NotLoadedError{edge: "descendant"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NodeClosure) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case nodeclosure.FieldID, nodeclosure.FieldDepth:
			values[i] = new(sql.NullInt64)
		case nodeclosure.FieldAncestorID, nodeclosure.FieldDescendantID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NodeClosure fields.
func (_m *NodeClosure) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case nodeclosure.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case nodeclosure.FieldAncestorID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field ancestor_id", values[i])
			} else if value != nil {
				_m.AncestorID = *value
			}
		case nodeclosure.FieldDescendantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field descendant_id", values[i])
			} else if value != nil {
				_m.DescendantID = *value
			}
		case nodeclosure.FieldDepth:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field depth", values[i])
			} else if value.Valid {
				_m.Depth = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NodeClosure.
// This includes values selected through modifiers, order, etc.
func (_m *NodeClosure) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAncestor queries the "ancestor" edge of the NodeClosure entity.
func (_m *NodeClosure) QueryAncestor() *NodeQuery {
	return NewNodeClosureClient(_m.config).QueryAncestor(_m)
}

// QueryDescendant queries the "descendant" edge of the NodeClosure entity.
func (_m *NodeClosure) QueryDescendant() *NodeQuery {
	return NewNodeClosureClient(_m.config).QueryDescendant(_m)
}

// Update returns a builder for updating this NodeClosure.
// Note that you need to call NodeClosure.Unwrap() before calling this method if this NodeClosure
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *NodeClosure) Update() *NodeClosureUpdateOne {
	return NewNodeClosureClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the NodeClosure entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *NodeClosure) Unwrap() *NodeClosure {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: NodeClosure is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *NodeClosure) String() string {
	var builder strings.Builder
	builder.WriteString("NodeClosure(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ancestor_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AncestorID))
	builder.WriteString(", ")
	builder.WriteString("descendant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DescendantID))
	builder.WriteString(", ")
	builder.WriteString("depth=")
	builder.WriteString(fmt.Sprintf("%v", _m.Depth))
	builder.WriteByte(')')
	return builder.String()
}

// NodeClosures is a parsable slice of NodeClosure.
type NodeClosures []*NodeClosure
