// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"profen/internal/data/ent/node"
	"profen/internal/data/ent/nodeclosure"
	"profen/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// NodeClosureUpdate is the builder for updating NodeClosure entities.
type NodeClosureUpdate struct {
	config
	hooks    []Hook
	mutation *NodeClosureMutation
}

// Where appends a list predicates to the NodeClosureUpdate builder.
func (_u *NodeClosureUpdate) Where(ps ...predicate.NodeClosure) *NodeClosureUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAncestorID sets the "ancestor_id" field.
func (_u *NodeClosureUpdate) SetAncestorID(v uuid.UUID) *NodeClosureUpdate {
	_u.mutation.SetAncestorID(v)
	return _u
}

// SetNillableAncestorID sets the "ancestor_id" field if the given value is not nil.
func (_u *NodeClosureUpdate) SetNillableAncestorID(v *uuid.UUID) *NodeClosureUpdate {
	if v != nil {
		_u.SetAncestorID(*v)
	}
	return _u
}

// SetDescendantID sets the "descendant_id" field.
func (_u *NodeClosureUpdate) SetDescendantID(v uuid.UUID) *NodeClosureUpdate {
	_u.mutation.SetDescendantID(v)
	return _u
}

// SetNillableDescendantID sets the "descendant_id" field if the given value is not nil.
func (_u *NodeClosureUpdate) SetNillableDescendantID(v *uuid.UUID) *NodeClosureUpdate {
	if v != nil {
		_u.SetDescendantID(*v)
	}
	return _u
}

// SetDepth sets the "depth" field.
func (_u *NodeClosureUpdate) SetDepth(v int) *NodeClosureUpdate {
	_u.mutation.ResetDepth()
	_u.mutation.SetDepth(v)
	return _u
}

// SetNillableDepth sets the "depth" field if the given value is not nil.
func (_u *NodeClosureUpdate) SetNillableDepth(v *int) *NodeClosureUpdate {
	if v != nil {
		_u.SetDepth(*v)
	}
	return _u
}

// AddDepth adds value to the "depth" field.
func (_u *NodeClosureUpdate) AddDepth(v int) *NodeClosureUpdate {
	_u.mutation.AddDepth(v)
	return _u
}

// SetAncestor sets the "ancestor" edge to the Node entity.
func (_u *NodeClosureUpdate) SetAncestor(v *Node) *NodeClosureUpdate {
	return _u.SetAncestorID(v.ID)
}

// SetDescendant sets the "descendant" edge to the Node entity.
func (_u *NodeClosureUpdate) SetDescendant(v *Node) *NodeClosureUpdate {
	return _u.SetDescendantID(v.ID)
}

// Mutation returns the NodeClosureMutation object of the builder.
func (_u *NodeClosureUpdate) Mutation() *NodeClosureMutation {
	return _u.mutation
}

// ClearAncestor clears the "ancestor" edge to the Node entity.
func (_u *NodeClosureUpdate) ClearAncestor() *NodeClosureUpdate {
	_u.mutation.ClearAncestor()
	return _u
}

// ClearDescendant clears the "descendant" edge to the Node entity.
func (_u *NodeClosureUpdate) ClearDescendant() *NodeClosureUpdate {
	_u.mutation.ClearDescendant()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NodeClosureUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NodeClosureUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NodeClosureUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NodeClosureUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NodeClosureUpdate) check() error {
	if _u.mutation.AncestorCleared() && len(_u.mutation.AncestorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NodeClosure.ancestor"`)
	}
	if _u.mutation.DescendantCleared() && len(_u.mutation.DescendantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NodeClosure.descendant"`)
	}
	return nil
}

func (_u *NodeClosureUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(nodeclosure.Table, nodeclosure.Columns, sqlgraph.NewFieldSpec(nodeclosure.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Depth(); ok {
		_spec.SetField(nodeclosure.FieldDepth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDepth(); ok {
		_spec.AddField(nodeclosure.FieldDepth, field.TypeInt, value)
	}
	if _u.mutation.AncestorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   nodeclosure.AncestorTable,
			Columns: []string{nodeclosure.AncestorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AncestorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   nodeclosure.AncestorTable,
			Columns: []string{nodeclosure.AncestorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DescendantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   nodeclosure.DescendantTable,
			Columns: []string{nodeclosure.DescendantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DescendantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   nodeclosure.DescendantTable,
			Columns: []string{nodeclosure.DescendantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{nodeclosure.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NodeClosureUpdateOne is the builder for updating a single NodeClosure entity.
type NodeClosureUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NodeClosureMutation
}

// SetAncestorID sets the "ancestor_id" field.
func (_u *NodeClosureUpdateOne) SetAncestorID(v uuid.UUID) *NodeClosureUpdateOne {
	_u.mutation.SetAncestorID(v)
	return _u
}

// SetNillableAncestorID sets the "ancestor_id" field if the given value is not nil.
func (_u *NodeClosureUpdateOne) SetNillableAncestorID(v *uuid.UUID) *NodeClosureUpdateOne {
	if v != nil {
		_u.SetAncestorID(*v)
	}
	return _u
}

// SetDescendantID sets the "descendant_id" field.
func (_u *NodeClosureUpdateOne) SetDescendantID(v uuid.UUID) *NodeClosureUpdateOne {
	_u.mutation.SetDescendantID(v)
	return _u
}

// SetNillableDescendantID sets the "descendant_id" field if the given value is not nil.
func (_u *NodeClosureUpdateOne) SetNillableDescendantID(v *uuid.UUID) *NodeClosureUpdateOne {
	if v != nil {
		_u.SetDescendantID(*v)
	}
	return _u
}

// SetDepth sets the "depth" field.
func (_u *NodeClosureUpdateOne) SetDepth(v int) *NodeClosureUpdateOne {
	_u.mutation.ResetDepth()
	_u.mutation.SetDepth(v)
	return _u
}

// SetNillableDepth sets the "depth" field if the given value is not nil.
func (_u *NodeClosureUpdateOne) SetNillableDepth(v *int) *NodeClosureUpdateOne {
	if v != nil {
		_u.SetDepth(*v)
	}
	return _u
}

// AddDepth adds value to the "depth" field.
func (_u *NodeClosureUpdateOne) AddDepth(v int) *NodeClosureUpdateOne {
	_u.mutation.AddDepth(v)
	return _u
}

// SetAncestor sets the "ancestor" edge to the Node entity.
func (_u *NodeClosureUpdateOne) SetAncestor(v *Node) *NodeClosureUpdateOne {
	return _u.SetAncestorID(v.ID)
}

// SetDescendant sets the "descendant" edge to the Node entity.
func (_u *NodeClosureUpdateOne) SetDescendant(v *Node) *NodeClosureUpdateOne {
	return _u.SetDescendantID(v.ID)
}

// Mutation returns the NodeClosureMutation object of the builder.
func (_u *NodeClosureUpdateOne) Mutation() *NodeClosureMutation {
	return _u.mutation
}

// ClearAncestor clears the "ancestor" edge to the Node entity.
func (_u *NodeClosureUpdateOne) ClearAncestor() *NodeClosureUpdateOne {
	_u.mutation.ClearAncestor()
	return _u
}

// ClearDescendant clears the "descendant" edge to the Node entity.
func (_u *NodeClosureUpdateOne) ClearDescendant() *NodeClosureUpdateOne {
	_u.mutation.ClearDescendant()
	return _u
}

// Where appends a list predicates to the NodeClosureUpdate builder.
func (_u *NodeClosureUpdateOne) Where(ps ...predicate.NodeClosure) *NodeClosureUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NodeClosureUpdateOne) Select(field string, fields ...string) *NodeClosureUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NodeClosure entity.
func (_u *NodeClosureUpdateOne) Save(ctx context.Context) (*NodeClosure, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NodeClosureUpdateOne) SaveX(ctx context.Context) *NodeClosure {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NodeClosureUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NodeClosureUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NodeClosureUpdateOne) check() error {
	if _u.mutation.AncestorCleared() && len(_u.mutation.AncestorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NodeClosure.ancestor"`)
	}
	if _u.mutation.DescendantCleared() && len(_u.mutation.DescendantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NodeClosure.descendant"`)
	}
	return nil
}

func (_u *NodeClosureUpdateOne) sqlSave(ctx context.Context) (_node *NodeClosure, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(nodeclosure.Table, nodeclosure.Columns, sqlgraph.NewFieldSpec(nodeclosure.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NodeClosure.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, nodeclosure.FieldID)
		for _, f := range fields {
			if !nodeclosure.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != nodeclosure.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Depth(); ok {
		_spec.SetField(nodeclosure.FieldDepth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDepth(); ok {
		_spec.AddField(nodeclosure.FieldDepth, field.TypeInt, value)
	}
	if _u.mutation.AncestorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   nodeclosure.AncestorTable,
			Columns: []string{nodeclosure.AncestorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AncestorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   nodeclosure.AncestorTable,
			Columns: []string{nodeclosure.AncestorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DescendantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   nodeclosure.DescendantTable,
			Columns: []string{nodeclosure.DescendantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DescendantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   nodeclosure.DescendantTable,
			Columns: []string{nodeclosure.DescendantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &NodeClosure{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{nodeclosure.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
