// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"profen/internal/data/ent/node"
	"profen/internal/data/ent/nodeassociation"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// NodeAssociationCreate is the builder for creating a NodeAssociation entity.
type NodeAssociationCreate struct {
	config
	mutation *NodeAssociationMutation
	hooks    []Hook
}

// SetSourceID sets the "source_id" field.
func (_c *NodeAssociationCreate) SetSourceID(v uuid.UUID) *NodeAssociationCreate {
	_c.mutation.SetSourceID(v)
	return _c
}

// SetTargetID sets the "target_id" field.
func (_c *NodeAssociationCreate) SetTargetID(v uuid.UUID) *NodeAssociationCreate {
	_c.mutation.SetTargetID(v)
	return _c
}

// SetRelType sets the "rel_type" field.
func (_c *NodeAssociationCreate) SetRelType(v nodeassociation.RelType) *NodeAssociationCreate {
	_c.mutation.SetRelType(v)
	return _c
}

// SetSource sets the "source" edge to the Node entity.
func (_c *NodeAssociationCreate) SetSource(v *Node) *NodeAssociationCreate {
	return _c.SetSourceID(v.ID)
}

// SetTarget sets the "target" edge to the Node entity.
func (_c *NodeAssociationCreate) SetTarget(v *Node) *NodeAssociationCreate {
	return _c.SetTargetID(v.ID)
}

// Mutation returns the NodeAssociationMutation object of the builder.
func (_c *NodeAssociationCreate) Mutation() *NodeAssociationMutation {
	return _c.mutation
}

// Save creates the NodeAssociation in the database.
func (_c *NodeAssociationCreate) Save(ctx context.Context) (*NodeAssociation, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NodeAssociationCreate) SaveX(ctx context.Context) *NodeAssociation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NodeAssociationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NodeAssociationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NodeAssociationCreate) check() error {
	if _, ok := _c.mutation.SourceID(); !ok {
		return &ValidationError{Name: "source_id", err: errors.New(`ent: missing required field "NodeAssociation.source_id"`)}
	}
	if _, ok := _c.mutation.TargetID(); !ok {
		return &ValidationError{Name: "target_id", err: errors.New(`ent: missing required field "NodeAssociation.target_id"`)}
	}
	if _, ok := _c.mutation.RelType(); !ok {
		return &ValidationError{Name: "rel_type", err: errors.New(`ent: missing required field "NodeAssociation.rel_type"`)}
	}
	if v, ok := _c.mutation.RelType(); ok {
		if err := nodeassociation.RelTypeValidator(v); err != nil {
			return &ValidationError{Name: "rel_type", err: fmt.Errorf(`ent: validator failed for field "NodeAssociation.rel_type": %w`, err)}
		}
	}
	if len(_c.mutation.SourceIDs()) == 0 {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required edge "NodeAssociation.source"`)}
	}
	if len(_c.mutation.TargetIDs()) == 0 {
		return &ValidationError{Name: "target", err: errors.New(`ent: missing required edge "NodeAssociation.target"`)}
	}
	return nil
}

func (_c *NodeAssociationCreate) sqlSave(ctx context.Context) (*NodeAssociation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NodeAssociationCreate) createSpec() (*NodeAssociation, *sqlgraph.CreateSpec) {
	var (
		_node = &NodeAssociation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(nodeassociation.Table, sqlgraph.NewFieldSpec(nodeassociation.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.RelType(); ok {
		_spec.SetField(nodeassociation.FieldRelType, field.TypeEnum, value)
		_node.RelType = value
	}
	if nodes := _c.mutation.SourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   nodeassociation.SourceTable,
			Columns: []string{nodeassociation.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SourceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TargetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   nodeassociation.TargetTable,
			Columns: []string{nodeassociation.TargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TargetID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// NodeAssociationCreateBulk is the builder for creating many NodeAssociation entities in bulk.
type NodeAssociationCreateBulk struct {
	config
	err      error
	builders []*NodeAssociationCreate
}

// Save creates the NodeAssociation entities in the database.
func (_c *NodeAssociationCreateBulk) Save(ctx context.Context) ([]*NodeAssociation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NodeAssociation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NodeAssociationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NodeAssociationCreateBulk) SaveX(ctx context.Context) []*NodeAssociation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NodeAssociationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NodeAssociationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
