// Code generated by ent, DO NOT EDIT.

package ent

import (
	"profen/internal/data/ent/attempt"
	"profen/internal/data/ent/errordefinition"
	"profen/internal/data/ent/errorresolution"
	"profen/internal/data/ent/fsrscard"
	"profen/internal/data/ent/node"
	"profen/internal/data/ent/schema"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	attemptFields := schema.Attempt{}.Fields()
	_ = attemptFields
	// attemptDescDurationMs is the schema descriptor for duration_ms field.
	attemptDescDurationMs := attemptFields[2].Descriptor()
	// attempt.DefaultDurationMs holds the default value on creation for the duration_ms field.
	attempt.DefaultDurationMs = attemptDescDurationMs.Default.(int)
	// attemptDescCreatedAt is the schema descriptor for created_at field.
	attemptDescCreatedAt := attemptFields[6].Descriptor()
	// attempt.DefaultCreatedAt holds the default value on creation for the created_at field.
	attempt.DefaultCreatedAt = attemptDescCreatedAt.Default.(func() time.Time)
	// attemptDescID is the schema descriptor for id field.
	attemptDescID := attemptFields[0].Descriptor()
	// attempt.DefaultID holds the default value on creation for the id field.
	attempt.DefaultID = attemptDescID.Default.(func() uuid.UUID)
	errordefinitionFields := schema.ErrorDefinition{}.Fields()
	_ = errordefinitionFields
	// errordefinitionDescLabel is the schema descriptor for label field.
	errordefinitionDescLabel := errordefinitionFields[1].Descriptor()
	// errordefinition.LabelValidator is a validator for the "label" field. It is called by the builders before save.
	errordefinition.LabelValidator = errordefinitionDescLabel.Validators[0].(func(string) error)
	// errordefinitionDescBaseWeight is the schema descriptor for base_weight field.
	errordefinitionDescBaseWeight := errordefinitionFields[2].Descriptor()
	// errordefinition.DefaultBaseWeight holds the default value on creation for the base_weight field.
	errordefinition.DefaultBaseWeight = errordefinitionDescBaseWeight.Default.(float64)
	// errordefinitionDescIsSystem is the schema descriptor for is_system field.
	errordefinitionDescIsSystem := errordefinitionFields[3].Descriptor()
	// errordefinition.DefaultIsSystem holds the default value on creation for the is_system field.
	errordefinition.DefaultIsSystem = errordefinitionDescIsSystem.Default.(bool)
	// errordefinitionDescID is the schema descriptor for id field.
	errordefinitionDescID := errordefinitionFields[0].Descriptor()
	// errordefinition.DefaultID holds the default value on creation for the id field.
	errordefinition.DefaultID = errordefinitionDescID.Default.(func() uuid.UUID)
	errorresolutionFields := schema.ErrorResolution{}.Fields()
	_ = errorresolutionFields
	// errorresolutionDescErrorType is the schema descriptor for error_type field.
	errorresolutionDescErrorType := errorresolutionFields[2].Descriptor()
	// errorresolution.ErrorTypeValidator is a validator for the "error_type" field. It is called by the builders before save.
	errorresolution.ErrorTypeValidator = errorresolutionDescErrorType.Validators[0].(func(string) error)
	// errorresolutionDescWeightImpact is the schema descriptor for weight_impact field.
	errorresolutionDescWeightImpact := errorresolutionFields[3].Descriptor()
	// errorresolution.DefaultWeightImpact holds the default value on creation for the weight_impact field.
	errorresolution.DefaultWeightImpact = errorresolutionDescWeightImpact.Default.(float64)
	// errorresolutionDescIsResolved is the schema descriptor for is_resolved field.
	errorresolutionDescIsResolved := errorresolutionFields[4].Descriptor()
	// errorresolution.DefaultIsResolved holds the default value on creation for the is_resolved field.
	errorresolution.DefaultIsResolved = errorresolutionDescIsResolved.Default.(bool)
	// errorresolutionDescCreatedAt is the schema descriptor for created_at field.
	errorresolutionDescCreatedAt := errorresolutionFields[5].Descriptor()
	// errorresolution.DefaultCreatedAt holds the default value on creation for the created_at field.
	errorresolution.DefaultCreatedAt = errorresolutionDescCreatedAt.Default.(func() time.Time)
	// errorresolutionDescID is the schema descriptor for id field.
	errorresolutionDescID := errorresolutionFields[0].Descriptor()
	// errorresolution.DefaultID holds the default value on creation for the id field.
	errorresolution.DefaultID = errorresolutionDescID.Default.(func() uuid.UUID)
	fsrscardFields := schema.FsrsCard{}.Fields()
	_ = fsrscardFields
	// fsrscardDescStability is the schema descriptor for stability field.
	fsrscardDescStability := fsrscardFields[1].Descriptor()
	// fsrscard.DefaultStability holds the default value on creation for the stability field.
	fsrscard.DefaultStability = fsrscardDescStability.Default.(float64)
	// fsrscardDescDifficulty is the schema descriptor for difficulty field.
	fsrscardDescDifficulty := fsrscardFields[2].Descriptor()
	// fsrscard.DefaultDifficulty holds the default value on creation for the difficulty field.
	fsrscard.DefaultDifficulty = fsrscardDescDifficulty.Default.(float64)
	// fsrscardDescElapsedDays is the schema descriptor for elapsed_days field.
	fsrscardDescElapsedDays := fsrscardFields[3].Descriptor()
	// fsrscard.DefaultElapsedDays holds the default value on creation for the elapsed_days field.
	fsrscard.DefaultElapsedDays = fsrscardDescElapsedDays.Default.(int)
	// fsrscardDescScheduledDays is the schema descriptor for scheduled_days field.
	fsrscardDescScheduledDays := fsrscardFields[4].Descriptor()
	// fsrscard.DefaultScheduledDays holds the default value on creation for the scheduled_days field.
	fsrscard.DefaultScheduledDays = fsrscardDescScheduledDays.Default.(int)
	// fsrscardDescReps is the schema descriptor for reps field.
	fsrscardDescReps := fsrscardFields[5].Descriptor()
	// fsrscard.DefaultReps holds the default value on creation for the reps field.
	fsrscard.DefaultReps = fsrscardDescReps.Default.(int)
	// fsrscardDescLapses is the schema descriptor for lapses field.
	fsrscardDescLapses := fsrscardFields[6].Descriptor()
	// fsrscard.DefaultLapses holds the default value on creation for the lapses field.
	fsrscard.DefaultLapses = fsrscardDescLapses.Default.(int)
	// fsrscardDescDue is the schema descriptor for due field.
	fsrscardDescDue := fsrscardFields[9].Descriptor()
	// fsrscard.DefaultDue holds the default value on creation for the due field.
	fsrscard.DefaultDue = fsrscardDescDue.Default.(func() time.Time)
	// fsrscardDescID is the schema descriptor for id field.
	fsrscardDescID := fsrscardFields[0].Descriptor()
	// fsrscard.DefaultID holds the default value on creation for the id field.
	fsrscard.DefaultID = fsrscardDescID.Default.(func() uuid.UUID)
	nodeFields := schema.Node{}.Fields()
	_ = nodeFields
	// nodeDescCreatedAt is the schema descriptor for created_at field.
	nodeDescCreatedAt := nodeFields[4].Descriptor()
	// node.DefaultCreatedAt holds the default value on creation for the created_at field.
	node.DefaultCreatedAt = nodeDescCreatedAt.Default.(func() time.Time)
	// nodeDescID is the schema descriptor for id field.
	nodeDescID := nodeFields[0].Descriptor()
	// node.DefaultID holds the default value on creation for the id field.
	node.DefaultID = nodeDescID.Default.(func() uuid.UUID)
}
