// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Attempt is the predicate function for attempt builders.
type Attempt func(*sql.Selector)

// ErrorResolution is the predicate function for errorresolution builders.
type ErrorResolution func(*sql.Selector)

// ErrorType is the predicate function for errortype builders.
type ErrorType func(*sql.Selector)

// FsrsCard is the predicate function for fsrscard builders.
type FsrsCard func(*sql.Selector)

// Node is the predicate function for node builders.
type Node func(*sql.Selector)

// NodeAssociation is the predicate function for nodeassociation builders.
type NodeAssociation func(*sql.Selector)

// NodeClosure is the predicate function for nodeclosure builders.
type NodeClosure func(*sql.Selector)
