// Code generated by ent, DO NOT EDIT.

package nodeclosure

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the nodeclosure type in the database.
	Label = "node_closure"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAncestorID holds the string denoting the ancestor_id field in the database.
	FieldAncestorID = "ancestor_id"
	// FieldDescendantID holds the string denoting the descendant_id field in the database.
	FieldDescendantID = "descendant_id"
	// FieldDepth holds the string denoting the depth field in the database.
	FieldDepth = "depth"
	// EdgeAncestor holds the string denoting the ancestor edge name in mutations.
	EdgeAncestor = "ancestor"
	// EdgeDescendant holds the string denoting the descendant edge name in mutations.
	EdgeDescendant = "descendant"
	// NodeFieldID holds the string denoting the ID field of the Node.
	NodeFieldID = "node_id"
	// Table holds the table name of the nodeclosure in the database.
	Table = "node_closures"
	// AncestorTable is the table that holds the ancestor relation/edge.
	AncestorTable = "node_closures"
	// AncestorInverseTable is the table name for the Node entity.
	// It exists in this package in order to avoid circular dependency with the "node" package.
	AncestorInverseTable = "nodes"
	// AncestorColumn is the table column denoting the ancestor relation/edge.
	AncestorColumn = "ancestor_id"
	// DescendantTable is the table that holds the descendant relation/edge.
	DescendantTable = "node_closures"
	// DescendantInverseTable is the table name for the Node entity.
	// It exists in this package in order to avoid circular dependency with the "node" package.
	DescendantInverseTable = "nodes"
	// DescendantColumn is the table column denoting the descendant relation/edge.
	DescendantColumn = "descendant_id"
)

// Columns holds all SQL columns for nodeclosure fields.
var Columns = []string{
	FieldID,
	FieldAncestorID,
	FieldDescendantID,
	FieldDepth,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the NodeClosure queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAncestorID orders the results by the ancestor_id field.
func ByAncestorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAncestorID, opts...).ToFunc()
}

// ByDescendantID orders the results by the descendant_id field.
func ByDescendantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescendantID, opts...).ToFunc()
}

// ByDepth orders the results by the depth field.
func ByDepth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDepth, opts...).ToFunc()
}

// ByAncestorField orders the results by ancestor field.
func ByAncestorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAncestorStep(), sql.OrderByField(field, opts...))
	}
}

// ByDescendantField orders the results by descendant field.
func ByDescendantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDescendantStep(), sql.OrderByField(field, opts...))
	}
}
func newAncestorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AncestorInverseTable, NodeFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AncestorTable, AncestorColumn),
	)
}
func newDescendantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DescendantInverseTable, NodeFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DescendantTable, DescendantColumn),
	)
}
