// Code generated by ent, DO NOT EDIT.

package attempt

import (
	"profen/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Attempt {
	return predicate.Attempt(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Attempt {
	return predicate.Attempt(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Attempt {
	return predicate.Attempt(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Attempt {
	return predicate.Attempt(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Attempt {
	return predicate.Attempt(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Attempt {
	return predicate.Attempt(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Attempt {
	return predicate.Attempt(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Attempt {
	return predicate.Attempt(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Attempt {
	return predicate.Attempt(sql.FieldLTE(FieldID, id))
}

// Rating applies equality check predicate on the "rating" field. It's identical to RatingEQ.
func Rating(v int) predicate.Attempt {
	return predicate.Attempt(sql.FieldEQ(FieldRating, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int) predicate.Attempt {
	return predicate.Attempt(sql.FieldEQ(FieldDurationMs, v))
}

// Stability applies equality check predicate on the "stability" field. It's identical to StabilityEQ.
func Stability(v float64) predicate.Attempt {
	return predicate.Attempt(sql.FieldEQ(FieldStability, v))
}

// Difficulty applies equality check predicate on the "difficulty" field. It's identical to DifficultyEQ.
func Difficulty(v float64) predicate.Attempt {
	return predicate.Attempt(sql.FieldEQ(FieldDifficulty, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Attempt {
	return predicate.Attempt(sql.FieldEQ(FieldCreatedAt, v))
}

// CardID applies equality check predicate on the "card_id" field. It's identical to CardIDEQ.
func CardID(v uuid.UUID) predicate.Attempt {
	return predicate.Attempt(sql.FieldEQ(FieldCardID, v))
}

// IsCorrect applies equality check predicate on the "is_correct" field. It's identical to IsCorrectEQ.
func IsCorrect(v bool) predicate.Attempt {
	return predicate.Attempt(sql.FieldEQ(FieldIsCorrect, v))
}

// ErrorTypeID applies equality check predicate on the "error_type_id" field. It's identical to ErrorTypeIDEQ.
func ErrorTypeID(v uuid.UUID) predicate.Attempt {
	return predicate.Attempt(sql.FieldEQ(FieldErrorTypeID, v))
}

// UserAnswer applies equality check predicate on the "user_answer" field. It's identical to UserAnswerEQ.
func UserAnswer(v string) predicate.Attempt {
	return predicate.Attempt(sql.FieldEQ(FieldUserAnswer, v))
}

// RatingEQ applies the EQ predicate on the "rating" field.
func RatingEQ(v int) predicate.Attempt {
	return predicate.Attempt(sql.FieldEQ(FieldRating, v))
}

// RatingNEQ applies the NEQ predicate on the "rating" field.
func RatingNEQ(v int) predicate.Attempt {
	return predicate.Attempt(sql.FieldNEQ(FieldRating, v))
}

// RatingIn applies the In predicate on the "rating" field.
func RatingIn(vs ...int) predicate.Attempt {
	return predicate.Attempt(sql.FieldIn(FieldRating, vs...))
}

// RatingNotIn applies the NotIn predicate on the "rating" field.
func RatingNotIn(vs ...int) predicate.Attempt {
	return predicate.Attempt(sql.FieldNotIn(FieldRating, vs...))
}

// RatingGT applies the GT predicate on the "rating" field.
func RatingGT(v int) predicate.Attempt {
	return predicate.Attempt(sql.FieldGT(FieldRating, v))
}

// RatingGTE applies the GTE predicate on the "rating" field.
func RatingGTE(v int) predicate.Attempt {
	return predicate.Attempt(sql.FieldGTE(FieldRating, v))
}

// RatingLT applies the LT predicate on the "rating" field.
func RatingLT(v int) predicate.Attempt {
	return predicate.Attempt(sql.FieldLT(FieldRating, v))
}

// RatingLTE applies the LTE predicate on the "rating" field.
func RatingLTE(v int) predicate.Attempt {
	return predicate.Attempt(sql.FieldLTE(FieldRating, v))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int) predicate.Attempt {
	return predicate.Attempt(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int) predicate.Attempt {
	return predicate.Attempt(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int) predicate.Attempt {
	return predicate.Attempt(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int) predicate.Attempt {
	return predicate.Attempt(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int) predicate.Attempt {
	return predicate.Attempt(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int) predicate.Attempt {
	return predicate.Attempt(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int) predicate.Attempt {
	return predicate.Attempt(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int) predicate.Attempt {
	return predicate.Attempt(sql.FieldLTE(FieldDurationMs, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v State) predicate.Attempt {
	return predicate.Attempt(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v State) predicate.Attempt {
	return predicate.Attempt(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...State) predicate.Attempt {
	return predicate.Attempt(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...State) predicate.Attempt {
	return predicate.Attempt(sql.FieldNotIn(FieldState, vs...))
}

// StabilityEQ applies the EQ predicate on the "stability" field.
func StabilityEQ(v float64) predicate.Attempt {
	return predicate.Attempt(sql.FieldEQ(FieldStability, v))
}

// StabilityNEQ applies the NEQ predicate on the "stability" field.
func StabilityNEQ(v float64) predicate.Attempt {
	return predicate.Attempt(sql.FieldNEQ(FieldStability, v))
}

// StabilityIn applies the In predicate on the "stability" field.
func StabilityIn(vs ...float64) predicate.Attempt {
	return predicate.Attempt(sql.FieldIn(FieldStability, vs...))
}

// StabilityNotIn applies the NotIn predicate on the "stability" field.
func StabilityNotIn(vs ...float64) predicate.Attempt {
	return predicate.Attempt(sql.FieldNotIn(FieldStability, vs...))
}

// StabilityGT applies the GT predicate on the "stability" field.
func StabilityGT(v float64) predicate.Attempt {
	return predicate.Attempt(sql.FieldGT(FieldStability, v))
}

// StabilityGTE applies the GTE predicate on the "stability" field.
func StabilityGTE(v float64) predicate.Attempt {
	return predicate.Attempt(sql.FieldGTE(FieldStability, v))
}

// StabilityLT applies the LT predicate on the "stability" field.
func StabilityLT(v float64) predicate.Attempt {
	return predicate.Attempt(sql.FieldLT(FieldStability, v))
}

// StabilityLTE applies the LTE predicate on the "stability" field.
func StabilityLTE(v float64) predicate.Attempt {
	return predicate.Attempt(sql.FieldLTE(FieldStability, v))
}

// DifficultyEQ applies the EQ predicate on the "difficulty" field.
func DifficultyEQ(v float64) predicate.Attempt {
	return predicate.Attempt(sql.FieldEQ(FieldDifficulty, v))
}

// DifficultyNEQ applies the NEQ predicate on the "difficulty" field.
func DifficultyNEQ(v float64) predicate.Attempt {
	return predicate.Attempt(sql.FieldNEQ(FieldDifficulty, v))
}

// DifficultyIn applies the In predicate on the "difficulty" field.
func DifficultyIn(vs ...float64) predicate.Attempt {
	return predicate.Attempt(sql.FieldIn(FieldDifficulty, vs...))
}

// DifficultyNotIn applies the NotIn predicate on the "difficulty" field.
func DifficultyNotIn(vs ...float64) predicate.Attempt {
	return predicate.Attempt(sql.FieldNotIn(FieldDifficulty, vs...))
}

// DifficultyGT applies the GT predicate on the "difficulty" field.
func DifficultyGT(v float64) predicate.Attempt {
	return predicate.Attempt(sql.FieldGT(FieldDifficulty, v))
}

// DifficultyGTE applies the GTE predicate on the "difficulty" field.
func DifficultyGTE(v float64) predicate.Attempt {
	return predicate.Attempt(sql.FieldGTE(FieldDifficulty, v))
}

// DifficultyLT applies the LT predicate on the "difficulty" field.
func DifficultyLT(v float64) predicate.Attempt {
	return predicate.Attempt(sql.FieldLT(FieldDifficulty, v))
}

// DifficultyLTE applies the LTE predicate on the "difficulty" field.
func DifficultyLTE(v float64) predicate.Attempt {
	return predicate.Attempt(sql.FieldLTE(FieldDifficulty, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Attempt {
	return predicate.Attempt(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Attempt {
	return predicate.Attempt(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Attempt {
	return predicate.Attempt(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Attempt {
	return predicate.Attempt(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Attempt {
	return predicate.Attempt(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Attempt {
	return predicate.Attempt(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Attempt {
	return predicate.Attempt(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Attempt {
	return predicate.Attempt(sql.FieldLTE(FieldCreatedAt, v))
}

// CardIDEQ applies the EQ predicate on the "card_id" field.
func CardIDEQ(v uuid.UUID) predicate.Attempt {
	return predicate.Attempt(sql.FieldEQ(FieldCardID, v))
}

// CardIDNEQ applies the NEQ predicate on the "card_id" field.
func CardIDNEQ(v uuid.UUID) predicate.Attempt {
	return predicate.Attempt(sql.FieldNEQ(FieldCardID, v))
}

// CardIDIn applies the In predicate on the "card_id" field.
func CardIDIn(vs ...uuid.UUID) predicate.Attempt {
	return predicate.Attempt(sql.FieldIn(FieldCardID, vs...))
}

// CardIDNotIn applies the NotIn predicate on the "card_id" field.
func CardIDNotIn(vs ...uuid.UUID) predicate.Attempt {
	return predicate.Attempt(sql.FieldNotIn(FieldCardID, vs...))
}

// IsCorrectEQ applies the EQ predicate on the "is_correct" field.
func IsCorrectEQ(v bool) predicate.Attempt {
	return predicate.Attempt(sql.FieldEQ(FieldIsCorrect, v))
}

// IsCorrectNEQ applies the NEQ predicate on the "is_correct" field.
func IsCorrectNEQ(v bool) predicate.Attempt {
	return predicate.Attempt(sql.FieldNEQ(FieldIsCorrect, v))
}

// ErrorTypeIDEQ applies the EQ predicate on the "error_type_id" field.
func ErrorTypeIDEQ(v uuid.UUID) predicate.Attempt {
	return predicate.Attempt(sql.FieldEQ(FieldErrorTypeID, v))
}

// ErrorTypeIDNEQ applies the NEQ predicate on the "error_type_id" field.
func ErrorTypeIDNEQ(v uuid.UUID) predicate.Attempt {
	return predicate.Attempt(sql.FieldNEQ(FieldErrorTypeID, v))
}

// ErrorTypeIDIn applies the In predicate on the "error_type_id" field.
func ErrorTypeIDIn(vs ...uuid.UUID) predicate.Attempt {
	return predicate.Attempt(sql.FieldIn(FieldErrorTypeID, vs...))
}

// ErrorTypeIDNotIn applies the NotIn predicate on the "error_type_id" field.
func ErrorTypeIDNotIn(vs ...uuid.UUID) predicate.Attempt {
	return predicate.Attempt(sql.FieldNotIn(FieldErrorTypeID, vs...))
}

// ErrorTypeIDIsNil applies the IsNil predicate on the "error_type_id" field.
func ErrorTypeIDIsNil() predicate.Attempt {
	return predicate.Attempt(sql.FieldIsNull(FieldErrorTypeID))
}

// ErrorTypeIDNotNil applies the NotNil predicate on the "error_type_id" field.
func ErrorTypeIDNotNil() predicate.Attempt {
	return predicate.Attempt(sql.FieldNotNull(FieldErrorTypeID))
}

// UserAnswerEQ applies the EQ predicate on the "user_answer" field.
func UserAnswerEQ(v string) predicate.Attempt {
	return predicate.Attempt(sql.FieldEQ(FieldUserAnswer, v))
}

// UserAnswerNEQ applies the NEQ predicate on the "user_answer" field.
func UserAnswerNEQ(v string) predicate.Attempt {
	return predicate.Attempt(sql.FieldNEQ(FieldUserAnswer, v))
}

// UserAnswerIn applies the In predicate on the "user_answer" field.
func UserAnswerIn(vs ...string) predicate.Attempt {
	return predicate.Attempt(sql.FieldIn(FieldUserAnswer, vs...))
}

// UserAnswerNotIn applies the NotIn predicate on the "user_answer" field.
func UserAnswerNotIn(vs ...string) predicate.Attempt {
	return predicate.Attempt(sql.FieldNotIn(FieldUserAnswer, vs...))
}

// UserAnswerGT applies the GT predicate on the "user_answer" field.
func UserAnswerGT(v string) predicate.Attempt {
	return predicate.Attempt(sql.FieldGT(FieldUserAnswer, v))
}

// UserAnswerGTE applies the GTE predicate on the "user_answer" field.
func UserAnswerGTE(v string) predicate.Attempt {
	return predicate.Attempt(sql.FieldGTE(FieldUserAnswer, v))
}

// UserAnswerLT applies the LT predicate on the "user_answer" field.
func UserAnswerLT(v string) predicate.Attempt {
	return predicate.Attempt(sql.FieldLT(FieldUserAnswer, v))
}

// UserAnswerLTE applies the LTE predicate on the "user_answer" field.
func UserAnswerLTE(v string) predicate.Attempt {
	return predicate.Attempt(sql.FieldLTE(FieldUserAnswer, v))
}

// UserAnswerContains applies the Contains predicate on the "user_answer" field.
func UserAnswerContains(v string) predicate.Attempt {
	return predicate.Attempt(sql.FieldContains(FieldUserAnswer, v))
}

// UserAnswerHasPrefix applies the HasPrefix predicate on the "user_answer" field.
func UserAnswerHasPrefix(v string) predicate.Attempt {
	return predicate.Attempt(sql.FieldHasPrefix(FieldUserAnswer, v))
}

// UserAnswerHasSuffix applies the HasSuffix predicate on the "user_answer" field.
func UserAnswerHasSuffix(v string) predicate.Attempt {
	return predicate.Attempt(sql.FieldHasSuffix(FieldUserAnswer, v))
}

// UserAnswerIsNil applies the IsNil predicate on the "user_answer" field.
func UserAnswerIsNil() predicate.Attempt {
	return predicate.Attempt(sql.FieldIsNull(FieldUserAnswer))
}

// UserAnswerNotNil applies the NotNil predicate on the "user_answer" field.
func UserAnswerNotNil() predicate.Attempt {
	return predicate.Attempt(sql.FieldNotNull(FieldUserAnswer))
}

// UserAnswerEqualFold applies the EqualFold predicate on the "user_answer" field.
func UserAnswerEqualFold(v string) predicate.Attempt {
	return predicate.Attempt(sql.FieldEqualFold(FieldUserAnswer, v))
}

// UserAnswerContainsFold applies the ContainsFold predicate on the "user_answer" field.
func UserAnswerContainsFold(v string) predicate.Attempt {
	return predicate.Attempt(sql.FieldContainsFold(FieldUserAnswer, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.Attempt {
	return predicate.Attempt(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.Attempt {
	return predicate.Attempt(sql.FieldNotNull(FieldMetadata))
}

// HasCard applies the HasEdge predicate on the "card" edge.
func HasCard() predicate.Attempt {
	return predicate.Attempt(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CardTable, CardColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCardWith applies the HasEdge predicate on the "card" edge with a given conditions (other predicates).
func HasCardWith(preds ...predicate.FsrsCard) predicate.Attempt {
	return predicate.Attempt(func(s *sql.Selector) {
		step := newCardStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasErrorDefinition applies the HasEdge predicate on the "error_definition" edge.
func HasErrorDefinition() predicate.Attempt {
	return predicate.Attempt(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ErrorDefinitionTable, ErrorDefinitionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasErrorDefinitionWith applies the HasEdge predicate on the "error_definition" edge with a given conditions (other predicates).
func HasErrorDefinitionWith(preds ...predicate.ErrorDefinition) predicate.Attempt {
	return predicate.Attempt(func(s *sql.Selector) {
		step := newErrorDefinitionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Attempt) predicate.Attempt {
	return predicate.Attempt(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Attempt) predicate.Attempt {
	return predicate.Attempt(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Attempt) predicate.Attempt {
	return predicate.Attempt(sql.NotPredicates(p))
}
