// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChildren(arg1) {
  return window['go']['app']['App']['GetChildren'](arg1);
}

export function GetDueCards(arg1) {
  return window['go']['app']['App']['GetDueCards'](arg1);
}

export function GetNode(arg1) {
  return window['go']['app']['App']['GetNode'](arg1);
}

export function GetSubjects() {
  return window['go']['app']['App']['GetSubjects']();
}

export function ReviewCard(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ReviewCard'](arg1, arg2, arg3, arg4);
}
