// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAssociation(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateAssociation'](arg1, arg2, arg3);
}

export function CreateNode(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateNode'](arg1, arg2, arg3);
}

export function DeleteNode(arg1) {
  return window['go']['app']['App']['DeleteNode'](arg1);
}

export function DuplicateNode(arg1) {
  return window['go']['app']['App']['DuplicateNode'](arg1);
}

export function GetAttemptDetails(arg1) {
  return window['go']['app']['App']['GetAttemptDetails'](arg1);
}

export function GetAttemptHistory(arg1) {
  return window['go']['app']['App']['GetAttemptHistory'](arg1);
}

export function GetChildren(arg1) {
  return window['go']['app']['App']['GetChildren'](arg1);
}

export function GetDashboardStats() {
  return window['go']['app']['App']['GetDashboardStats']();
}

export function GetDueCards(arg1) {
  return window['go']['app']['App']['GetDueCards'](arg1);
}

export function GetNode(arg1) {
  return window['go']['app']['App']['GetNode'](arg1);
}

export function GetNodeAssociations(arg1) {
  return window['go']['app']['App']['GetNodeAssociations'](arg1);
}

export function GetNodeBreadcrumbs(arg1) {
  return window['go']['app']['App']['GetNodeBreadcrumbs'](arg1);
}

export function GetNodeMastery(arg1) {
  return window['go']['app']['App']['GetNodeMastery'](arg1);
}

export function GetRelatedNodes(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetRelatedNodes'](arg1, arg2, arg3);
}

export function GetSchedulingInfo(arg1) {
  return window['go']['app']['App']['GetSchedulingInfo'](arg1);
}

export function GetSubjects() {
  return window['go']['app']['App']['GetSubjects']();
}

export function IsFullscreen() {
  return window['go']['app']['App']['IsFullscreen']();
}

export function ReviewCard(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ReviewCard'](arg1, arg2, arg3, arg4);
}

export function SearchNodes(arg1) {
  return window['go']['app']['App']['SearchNodes'](arg1);
}

export function ToggleFullscreen() {
  return window['go']['app']['App']['ToggleFullscreen']();
}

export function UpdateNode(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateNode'](arg1, arg2, arg3);
}
