// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ent} from '../models';

export function CreateNode(arg1:string,arg2:string,arg3:string):Promise<ent.Node>;

export function GetChildren(arg1:string):Promise<Array<ent.Node>>;

export function GetDueCards(arg1:number):Promise<Array<ent.Node>>;

export function GetNode(arg1:string):Promise<ent.Node>;

export function GetSubjects():Promise<Array<ent.Node>>;

export function ReviewCard(arg1:string,arg2:number,arg3:number,arg4:string):Promise<ent.FsrsCard>;

export function UpdateNode(arg1:string,arg2:string,arg3:string):Promise<ent.Node>;
