// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ent} from '../models';
import {data} from '../models';

export function CreateAssociation(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateNode(arg1:string,arg2:string,arg3:string):Promise<ent.Node>;

export function DeleteNode(arg1:string):Promise<void>;

export function DuplicateNode(arg1:string):Promise<ent.Node>;

export function GetAttemptDetails(arg1:string):Promise<Record<string, any>>;

export function GetAttemptHistory(arg1:string):Promise<Array<ent.Attempt>>;

export function GetChildren(arg1:string):Promise<Array<ent.Node>>;

export function GetDashboardStats():Promise<data.DashboardStats>;

export function GetDueCards(arg1:number):Promise<Array<ent.Node>>;

export function GetNode(arg1:string):Promise<ent.Node>;

export function GetNodeAssociations(arg1:string):Promise<Array<ent.NodeAssociation>>;

export function GetNodeBreadcrumbs(arg1:string):Promise<Array<ent.Node>>;

export function GetNodeMastery(arg1:string):Promise<Record<string, any>>;

export function GetRelatedNodes(arg1:string,arg2:string,arg3:string):Promise<Array<ent.Node>>;

export function GetSchedulingInfo(arg1:string):Promise<Record<number, string>>;

export function GetSubjects():Promise<Array<ent.Node>>;

export function IsFullscreen():Promise<boolean>;

export function ReviewCard(arg1:string,arg2:number,arg3:number,arg4:string):Promise<void>;

export function SearchNodes(arg1:string):Promise<Array<ent.Node>>;

export function ToggleFullscreen():Promise<void>;

export function UpdateNode(arg1:string,arg2:string,arg3:string):Promise<ent.Node>;
