// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AttemptsColumns holds the columns for the "attempts" table.
	AttemptsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// AttemptsTable holds the schema information for the "attempts" table.
	AttemptsTable = &schema.Table{
		Name:       "attempts",
		Columns:    AttemptsColumns,
		PrimaryKey: []*schema.Column{AttemptsColumns[0]},
	}
	// ErrorResolutionsColumns holds the columns for the "error_resolutions" table.
	ErrorResolutionsColumns = []*schema.Column{
		{Name: "resolution_id", Type: field.TypeUUID},
		{Name: "error_type", Type: field.TypeString},
		{Name: "weight_impact", Type: field.TypeFloat64, Default: 1},
		{Name: "is_resolved", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "resolved_at", Type: field.TypeTime, Nullable: true},
		{Name: "node_id", Type: field.TypeUUID},
	}
	// ErrorResolutionsTable holds the schema information for the "error_resolutions" table.
	ErrorResolutionsTable = &schema.Table{
		Name:       "error_resolutions",
		Columns:    ErrorResolutionsColumns,
		PrimaryKey: []*schema.Column{ErrorResolutionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "error_resolutions_nodes_error_resolutions",
				Columns:    []*schema.Column{ErrorResolutionsColumns[6]},
				RefColumns: []*schema.Column{NodesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ErrorTypesColumns holds the columns for the "error_types" table.
	ErrorTypesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// ErrorTypesTable holds the schema information for the "error_types" table.
	ErrorTypesTable = &schema.Table{
		Name:       "error_types",
		Columns:    ErrorTypesColumns,
		PrimaryKey: []*schema.Column{ErrorTypesColumns[0]},
	}
	// FsrsCardsColumns holds the columns for the "fsrs_cards" table.
	FsrsCardsColumns = []*schema.Column{
		{Name: "card_id", Type: field.TypeUUID},
		{Name: "stability", Type: field.TypeFloat64, Default: 0},
		{Name: "difficulty", Type: field.TypeFloat64, Default: 0},
		{Name: "elapsed_days", Type: field.TypeInt, Default: 0},
		{Name: "scheduled_days", Type: field.TypeInt, Default: 0},
		{Name: "reps", Type: field.TypeInt, Default: 0},
		{Name: "lapses", Type: field.TypeInt, Default: 0},
		{Name: "state", Type: field.TypeEnum, Enums: []string{"new", "learning", "review", "relearning"}, Default: "new"},
		{Name: "last_review", Type: field.TypeTime, Nullable: true},
		{Name: "due", Type: field.TypeTime},
		{Name: "node_id", Type: field.TypeUUID, Unique: true},
	}
	// FsrsCardsTable holds the schema information for the "fsrs_cards" table.
	FsrsCardsTable = &schema.Table{
		Name:       "fsrs_cards",
		Columns:    FsrsCardsColumns,
		PrimaryKey: []*schema.Column{FsrsCardsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "fsrs_cards_nodes_fsrs_card",
				Columns:    []*schema.Column{FsrsCardsColumns[10]},
				RefColumns: []*schema.Column{NodesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// NodesColumns holds the columns for the "nodes" table.
	NodesColumns = []*schema.Column{
		{Name: "node_id", Type: field.TypeUUID},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"subject", "topic", "problem", "theory", "term"}},
		{Name: "body", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "parent_id", Type: field.TypeUUID, Nullable: true},
	}
	// NodesTable holds the schema information for the "nodes" table.
	NodesTable = &schema.Table{
		Name:       "nodes",
		Columns:    NodesColumns,
		PrimaryKey: []*schema.Column{NodesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "nodes_nodes_children",
				Columns:    []*schema.Column{NodesColumns[5]},
				RefColumns: []*schema.Column{NodesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// NodeAssociationsColumns holds the columns for the "node_associations" table.
	NodeAssociationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "rel_type", Type: field.TypeEnum, Enums: []string{"prerequisite", "example", "tests", "similar_to", "defines", "translation_of", "translated_from", "variant_of", "source_variant"}},
		{Name: "source_id", Type: field.TypeUUID},
		{Name: "target_id", Type: field.TypeUUID},
	}
	// NodeAssociationsTable holds the schema information for the "node_associations" table.
	NodeAssociationsTable = &schema.Table{
		Name:       "node_associations",
		Columns:    NodeAssociationsColumns,
		PrimaryKey: []*schema.Column{NodeAssociationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "node_associations_nodes_outgoing_associations",
				Columns:    []*schema.Column{NodeAssociationsColumns[2]},
				RefColumns: []*schema.Column{NodesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "node_associations_nodes_incoming_associations",
				Columns:    []*schema.Column{NodeAssociationsColumns[3]},
				RefColumns: []*schema.Column{NodesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "nodeassociation_source_id_target_id_rel_type",
				Unique:  true,
				Columns: []*schema.Column{NodeAssociationsColumns[2], NodeAssociationsColumns[3], NodeAssociationsColumns[1]},
			},
		},
	}
	// NodeClosuresColumns holds the columns for the "node_closures" table.
	NodeClosuresColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "depth", Type: field.TypeInt},
		{Name: "ancestor_id", Type: field.TypeUUID},
		{Name: "descendant_id", Type: field.TypeUUID},
	}
	// NodeClosuresTable holds the schema information for the "node_closures" table.
	NodeClosuresTable = &schema.Table{
		Name:       "node_closures",
		Columns:    NodeClosuresColumns,
		PrimaryKey: []*schema.Column{NodeClosuresColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "node_closures_nodes_child_closures",
				Columns:    []*schema.Column{NodeClosuresColumns[2]},
				RefColumns: []*schema.Column{NodesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "node_closures_nodes_parent_closures",
				Columns:    []*schema.Column{NodeClosuresColumns[3]},
				RefColumns: []*schema.Column{NodesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "nodeclosure_ancestor_id_descendant_id",
				Unique:  true,
				Columns: []*schema.Column{NodeClosuresColumns[2], NodeClosuresColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AttemptsTable,
		ErrorResolutionsTable,
		ErrorTypesTable,
		FsrsCardsTable,
		NodesTable,
		NodeAssociationsTable,
		NodeClosuresTable,
	}
)

func init() {
	ErrorResolutionsTable.ForeignKeys[0].RefTable = NodesTable
	FsrsCardsTable.ForeignKeys[0].RefTable = NodesTable
	NodesTable.ForeignKeys[0].RefTable = NodesTable
	NodeAssociationsTable.ForeignKeys[0].RefTable = NodesTable
	NodeAssociationsTable.ForeignKeys[1].RefTable = NodesTable
	NodeAssociationsTable.Annotation = &entsql.Annotation{}
	NodeAssociationsTable.Annotation.Checks = map[string]string{
		"source_target_order": "source_id < target_id",
	}
	NodeClosuresTable.ForeignKeys[0].RefTable = NodesTable
	NodeClosuresTable.ForeignKeys[1].RefTable = NodesTable
}
