// Code generated by ent, DO NOT EDIT.

package nodeassociation

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the nodeassociation type in the database.
	Label = "node_association"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSourceID holds the string denoting the source_id field in the database.
	FieldSourceID = "source_id"
	// FieldTargetID holds the string denoting the target_id field in the database.
	FieldTargetID = "target_id"
	// FieldRelType holds the string denoting the rel_type field in the database.
	FieldRelType = "rel_type"
	// EdgeSource holds the string denoting the source edge name in mutations.
	EdgeSource = "source"
	// EdgeTarget holds the string denoting the target edge name in mutations.
	EdgeTarget = "target"
	// NodeFieldID holds the string denoting the ID field of the Node.
	NodeFieldID = "node_id"
	// Table holds the table name of the nodeassociation in the database.
	Table = "node_associations"
	// SourceTable is the table that holds the source relation/edge.
	SourceTable = "node_associations"
	// SourceInverseTable is the table name for the Node entity.
	// It exists in this package in order to avoid circular dependency with the "node" package.
	SourceInverseTable = "nodes"
	// SourceColumn is the table column denoting the source relation/edge.
	SourceColumn = "source_id"
	// TargetTable is the table that holds the target relation/edge.
	TargetTable = "node_associations"
	// TargetInverseTable is the table name for the Node entity.
	// It exists in this package in order to avoid circular dependency with the "node" package.
	TargetInverseTable = "nodes"
	// TargetColumn is the table column denoting the target relation/edge.
	TargetColumn = "target_id"
)

// Columns holds all SQL columns for nodeassociation fields.
var Columns = []string{
	FieldID,
	FieldSourceID,
	FieldTargetID,
	FieldRelType,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// RelType defines the type for the "rel_type" enum field.
type RelType string

// RelType values.
const (
	RelTypePrerequisite   RelType = "prerequisite"
	RelTypeExample        RelType = "example"
	RelTypeTests          RelType = "tests"
	RelTypeSimilarTo      RelType = "similar_to"
	RelTypeDefines        RelType = "defines"
	RelTypeTranslation    RelType = "translation"
	RelTypeTranslatedFrom RelType = "translated_from"
	RelTypeVariantOf      RelType = "variant_of"
	RelTypeSourceVariant  RelType = "source_variant"
)

func (rt RelType) String() string {
	return string(rt)
}

// RelTypeValidator is a validator for the "rel_type" field enum values. It is called by the builders before save.
func RelTypeValidator(rt RelType) error {
	switch rt {
	case RelTypePrerequisite, RelTypeExample, RelTypeTests, RelTypeSimilarTo, RelTypeDefines, RelTypeTranslation, RelTypeTranslatedFrom, RelTypeVariantOf, RelTypeSourceVariant:
		return nil
	default:
		return fmt.Errorf("nodeassociation: invalid enum value for rel_type field: %q", rt)
	}
}

// OrderOption defines the ordering options for the NodeAssociation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySourceID orders the results by the source_id field.
func BySourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceID, opts...).ToFunc()
}

// ByTargetID orders the results by the target_id field.
func ByTargetID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetID, opts...).ToFunc()
}

// ByRelType orders the results by the rel_type field.
func ByRelType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRelType, opts...).ToFunc()
}

// BySourceField orders the results by source field.
func BySourceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSourceStep(), sql.OrderByField(field, opts...))
	}
}

// ByTargetField orders the results by target field.
func ByTargetField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTargetStep(), sql.OrderByField(field, opts...))
	}
}
func newSourceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SourceInverseTable, NodeFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SourceTable, SourceColumn),
	)
}
func newTargetStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TargetInverseTable, NodeFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TargetTable, TargetColumn),
	)
}
