// Code generated by ent, DO NOT EDIT.

package nodeassociation

import (
	"profen/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.NodeAssociation {
	return predicate.NodeAssociation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.NodeAssociation {
	return predicate.NodeAssociation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.NodeAssociation {
	return predicate.NodeAssociation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.NodeAssociation {
	return predicate.NodeAssociation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.NodeAssociation {
	return predicate.NodeAssociation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.NodeAssociation {
	return predicate.NodeAssociation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.NodeAssociation {
	return predicate.NodeAssociation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.NodeAssociation {
	return predicate.NodeAssociation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.NodeAssociation {
	return predicate.NodeAssociation(sql.FieldLTE(FieldID, id))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v uuid.UUID) predicate.NodeAssociation {
	return predicate.NodeAssociation(sql.FieldEQ(FieldSourceID, v))
}

// TargetID applies equality check predicate on the "target_id" field. It's identical to TargetIDEQ.
func TargetID(v uuid.UUID) predicate.NodeAssociation {
	return predicate.NodeAssociation(sql.FieldEQ(FieldTargetID, v))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v uuid.UUID) predicate.NodeAssociation {
	return predicate.NodeAssociation(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v uuid.UUID) predicate.NodeAssociation {
	return predicate.NodeAssociation(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...uuid.UUID) predicate.NodeAssociation {
	return predicate.NodeAssociation(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...uuid.UUID) predicate.NodeAssociation {
	return predicate.NodeAssociation(sql.FieldNotIn(FieldSourceID, vs...))
}

// TargetIDEQ applies the EQ predicate on the "target_id" field.
func TargetIDEQ(v uuid.UUID) predicate.NodeAssociation {
	return predicate.NodeAssociation(sql.FieldEQ(FieldTargetID, v))
}

// TargetIDNEQ applies the NEQ predicate on the "target_id" field.
func TargetIDNEQ(v uuid.UUID) predicate.NodeAssociation {
	return predicate.NodeAssociation(sql.FieldNEQ(FieldTargetID, v))
}

// TargetIDIn applies the In predicate on the "target_id" field.
func TargetIDIn(vs ...uuid.UUID) predicate.NodeAssociation {
	return predicate.NodeAssociation(sql.FieldIn(FieldTargetID, vs...))
}

// TargetIDNotIn applies the NotIn predicate on the "target_id" field.
func TargetIDNotIn(vs ...uuid.UUID) predicate.NodeAssociation {
	return predicate.NodeAssociation(sql.FieldNotIn(FieldTargetID, vs...))
}

// RelTypeEQ applies the EQ predicate on the "rel_type" field.
func RelTypeEQ(v RelType) predicate.NodeAssociation {
	return predicate.NodeAssociation(sql.FieldEQ(FieldRelType, v))
}

// RelTypeNEQ applies the NEQ predicate on the "rel_type" field.
func RelTypeNEQ(v RelType) predicate.NodeAssociation {
	return predicate.NodeAssociation(sql.FieldNEQ(FieldRelType, v))
}

// RelTypeIn applies the In predicate on the "rel_type" field.
func RelTypeIn(vs ...RelType) predicate.NodeAssociation {
	return predicate.NodeAssociation(sql.FieldIn(FieldRelType, vs...))
}

// RelTypeNotIn applies the NotIn predicate on the "rel_type" field.
func RelTypeNotIn(vs ...RelType) predicate.NodeAssociation {
	return predicate.NodeAssociation(sql.FieldNotIn(FieldRelType, vs...))
}

// HasSource applies the HasEdge predicate on the "source" edge.
func HasSource() predicate.NodeAssociation {
	return predicate.NodeAssociation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SourceTable, SourceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSourceWith applies the HasEdge predicate on the "source" edge with a given conditions (other predicates).
func HasSourceWith(preds ...predicate.Node) predicate.NodeAssociation {
	return predicate.NodeAssociation(func(s *sql.Selector) {
		step := newSourceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTarget applies the HasEdge predicate on the "target" edge.
func HasTarget() predicate.NodeAssociation {
	return predicate.NodeAssociation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TargetTable, TargetColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTargetWith applies the HasEdge predicate on the "target" edge with a given conditions (other predicates).
func HasTargetWith(preds ...predicate.Node) predicate.NodeAssociation {
	return predicate.NodeAssociation(func(s *sql.Selector) {
		step := newTargetStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NodeAssociation) predicate.NodeAssociation {
	return predicate.NodeAssociation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NodeAssociation) predicate.NodeAssociation {
	return predicate.NodeAssociation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NodeAssociation) predicate.NodeAssociation {
	return predicate.NodeAssociation(sql.NotPredicates(p))
}
